-- RiderLink+ v8.6 founder-code and membership entitlements.
-- Run once in the Supabase SQL editor. Safe to run again.
create extension if not exists pgcrypto with schema extensions;

create table if not exists public.riderlink_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.riderlink_invite_codes (
  id uuid primary key default extensions.gen_random_uuid(),
  code_hash text not null unique,
  recipient_name text not null check (char_length(recipient_name) between 1 and 80),
  reward_type text not null check (reward_type in ('developer_lifetime','founder_lifetime','founder_price','complimentary')),
  complimentary_days integer check (complimentary_days between 1 and 3650),
  max_redemptions integer not null default 1 check (max_redemptions between 1 and 1000),
  redemption_count integer not null default 0 check (redemption_count >= 0),
  expires_at timestamptz,
  revoked boolean not null default false,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.riderlink_entitlements (
  user_id uuid primary key references auth.users(id) on delete cascade,
  tier text not null check (tier in ('developer','founder_lifetime','founder_price','complimentary')),
  plus_access boolean not null default false,
  founder_price_eligible boolean not null default false,
  expires_at timestamptz,
  source_code_id uuid references public.riderlink_invite_codes(id) on delete set null,
  granted_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

create table if not exists public.riderlink_redemptions (
  id bigint generated by default as identity primary key,
  code_id uuid not null references public.riderlink_invite_codes(id) on delete restrict,
  user_id uuid not null references auth.users(id) on delete cascade,
  redeemed_at timestamptz not null default now(),
  unique(code_id,user_id)
);

alter table public.riderlink_admins enable row level security;
alter table public.riderlink_invite_codes enable row level security;
alter table public.riderlink_entitlements enable row level security;
alter table public.riderlink_redemptions enable row level security;

drop policy if exists "members read own entitlement" on public.riderlink_entitlements;
create policy "members read own entitlement" on public.riderlink_entitlements
for select to authenticated using (user_id=auth.uid());

-- One-time bootstrap code for BobTheZombie. Only its SHA-256 hash is stored here.
-- Redeeming it grants permanent developer access and promotes that account to code manager.
insert into public.riderlink_invite_codes(code_hash,recipient_name,reward_type,max_redemptions)
values ('def0e55ac6a402b608b2c16cd9b67eb9aece0bfbcb4a094d6187738c8df162db','BobTheZombie','developer_lifetime',1)
on conflict (code_hash) do nothing;

create or replace function public.redeem_riderlink_code(p_code text)
returns table(tier text,plus_access boolean,founder_price_eligible boolean,expires_at timestamptz,is_admin boolean)
language plpgsql security definer set search_path=public,extensions as $$
declare c public.riderlink_invite_codes%rowtype;new_expiry timestamptz;
begin
  if auth.uid() is null then raise exception 'Sign in to RiderLink first'; end if;
  select * into c from public.riderlink_invite_codes
  where code_hash=encode(digest(upper(trim(p_code)),'sha256'),'hex') for update;
  if c.id is null then raise exception 'That RiderLink+ code is not valid'; end if;
  if c.revoked then raise exception 'That code has been revoked'; end if;
  if c.expires_at is not null and c.expires_at<=now() then raise exception 'That code has expired'; end if;
  if c.redemption_count>=c.max_redemptions and not exists(select 1 from public.riderlink_redemptions where code_id=c.id and user_id=auth.uid()) then raise exception 'That code has already been used'; end if;
  if not exists(select 1 from public.riderlink_redemptions where code_id=c.id and user_id=auth.uid()) then
    insert into public.riderlink_redemptions(code_id,user_id) values(c.id,auth.uid());
    update public.riderlink_invite_codes set redemption_count=redemption_count+1 where id=c.id;
  end if;
  new_expiry=case when c.reward_type='complimentary' then now()+make_interval(days=>coalesce(c.complimentary_days,30)) else null end;
  insert into public.riderlink_entitlements(user_id,tier,plus_access,founder_price_eligible,expires_at,source_code_id,granted_by)
  values(auth.uid(),case when c.reward_type='developer_lifetime' then 'developer' else c.reward_type end,
    c.reward_type in ('developer_lifetime','founder_lifetime','complimentary'),
    c.reward_type in ('developer_lifetime','founder_price'),new_expiry,c.id,c.created_by)
  on conflict(user_id) do update set
    tier=case when riderlink_entitlements.tier='developer' then riderlink_entitlements.tier else excluded.tier end,
    plus_access=riderlink_entitlements.plus_access or excluded.plus_access,
    founder_price_eligible=riderlink_entitlements.founder_price_eligible or excluded.founder_price_eligible,
    expires_at=case when riderlink_entitlements.tier='developer' or riderlink_entitlements.expires_at is null and riderlink_entitlements.plus_access then riderlink_entitlements.expires_at else excluded.expires_at end,
    source_code_id=excluded.source_code_id,updated_at=now();
  if c.reward_type='developer_lifetime' then insert into public.riderlink_admins(user_id) values(auth.uid()) on conflict do nothing; end if;
  return query select e.tier,e.plus_access and (e.expires_at is null or e.expires_at>now()),e.founder_price_eligible,e.expires_at,exists(select 1 from public.riderlink_admins a where a.user_id=auth.uid()) from public.riderlink_entitlements e where e.user_id=auth.uid();
end $$;

create or replace function public.my_riderlink_membership()
returns table(tier text,plus_access boolean,founder_price_eligible boolean,expires_at timestamptz,is_admin boolean)
language sql stable security definer set search_path=public as $$
  select coalesce(e.tier,'free'),coalesce(e.plus_access and (e.expires_at is null or e.expires_at>now()),false),coalesce(e.founder_price_eligible,false),e.expires_at,exists(select 1 from public.riderlink_admins a where a.user_id=auth.uid())
  from (select auth.uid() user_id) u left join public.riderlink_entitlements e on e.user_id=u.user_id;
$$;

create or replace function public.create_riderlink_code(p_name text,p_reward_type text,p_complimentary_days integer default null,p_expires_days integer default 30)
returns text language plpgsql security definer set search_path=public,extensions as $$
declare plain text;hash text;
begin
  if not exists(select 1 from public.riderlink_admins where user_id=auth.uid()) then raise exception 'Founder Code Manager access required'; end if;
  if trim(p_name)='' or char_length(trim(p_name))>80 then raise exception 'Enter a recipient name'; end if;
  if p_reward_type not in ('founder_lifetime','founder_price','complimentary') then raise exception 'Invalid reward type'; end if;
  plain='RLP-'||upper(encode(gen_random_bytes(6),'hex'))||'-'||upper(encode(gen_random_bytes(6),'hex'));
  hash=encode(digest(plain,'sha256'),'hex');
  insert into public.riderlink_invite_codes(code_hash,recipient_name,reward_type,complimentary_days,expires_at,created_by)
  values(hash,trim(p_name),p_reward_type,case when p_reward_type='complimentary' then coalesce(p_complimentary_days,30) end,now()+make_interval(days=>least(greatest(coalesce(p_expires_days,30),1),365)),auth.uid());
  return plain;
end $$;

create or replace function public.revoke_riderlink_entitlement(p_user uuid)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not exists(select 1 from public.riderlink_admins where user_id=auth.uid()) then raise exception 'Founder Code Manager access required'; end if;
  if p_user=auth.uid() then raise exception 'Developer access cannot revoke itself'; end if;
  delete from public.riderlink_entitlements where user_id=p_user;
end $$;

revoke all on function public.redeem_riderlink_code(text) from public;
revoke all on function public.my_riderlink_membership() from public;
revoke all on function public.create_riderlink_code(text,text,integer,integer) from public;
revoke all on function public.revoke_riderlink_entitlement(uuid) from public;
grant execute on function public.redeem_riderlink_code(text) to authenticated;
grant execute on function public.my_riderlink_membership() to authenticated;
grant execute on function public.create_riderlink_code(text,text,integer,integer) to authenticated;
grant execute on function public.revoke_riderlink_entitlement(uuid) to authenticated;
