-- RiderLink+ v8.7 Convoy Mode. Run after riderlink.sql and riderlink_membership_v86.sql.
alter table public.group_rides add column if not exists route_mode text not null default 'scooter_safe';
alter table public.group_rides add column if not exists avoid_highways boolean not null default true;
alter table public.group_rides add column if not exists updated_at timestamptz not null default now();

create table if not exists public.convoy_alerts (
  id bigint generated by default as identity primary key,
  ride_id bigint not null references public.group_rides(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  alert_type text not null check(alert_type in('regroup','fuel','mechanical','hazard','police','pull_over','ready')),
  message text not null check(char_length(message) between 1 and 120),
  latitude double precision check(latitude between -90 and 90),
  longitude double precision check(longitude between -180 and 180),
  created_at timestamptz not null default now()
);
create index if not exists convoy_alerts_ride_time on public.convoy_alerts(ride_id,created_at desc);
alter table public.convoy_alerts enable row level security;
drop policy if exists "convoy members read alerts" on public.convoy_alerts;
create policy "convoy members read alerts" on public.convoy_alerts for select to authenticated using(public.is_group_ride_member(ride_id));

create or replace function public.create_convoy(p_name text,p_destination text default '',p_avoid_highways boolean default true)
returns bigint language plpgsql security definer set search_path=public,extensions as $$
declare rid bigint;allowed boolean;
begin
  select coalesce(e.plus_access and (e.expires_at is null or e.expires_at>now()),false) or exists(select 1 from riderlink_admins a where a.user_id=auth.uid()) into allowed
  from (select auth.uid() id) u left join riderlink_entitlements e on e.user_id=u.id;
  if not allowed then raise exception 'Creating a convoy requires RiderLink+. You can still join a convoy for free.'; end if;
  if char_length(trim(p_name)) not between 3 and 60 then raise exception 'Convoy name must be 3-60 characters'; end if;
  insert into group_rides(owner_id,name,destination,invite_code,route_mode,avoid_highways,ends_at)
  values(auth.uid(),trim(p_name),left(trim(p_destination),160),upper(substr(encode(gen_random_bytes(6),'hex'),1,8)),'scooter_safe',coalesce(p_avoid_highways,true),now()+interval '12 hours') returning id into rid;
  insert into group_ride_members(ride_id,user_id,role) values(rid,auth.uid(),'leader');return rid;
end $$;

drop function if exists public.my_active_group_rides();
create function public.my_active_group_rides()
returns table(id bigint,name text,destination text,invite_code text,role text,member_count bigint,avoid_highways boolean,ends_at timestamptz)
language sql stable security definer set search_path=public as $$
 select r.id,r.name,r.destination,r.invite_code,m.role,(select count(*) from group_ride_members x where x.ride_id=r.id),r.avoid_highways,r.ends_at
 from group_ride_members m join group_rides r on r.id=m.ride_id
 where m.user_id=auth.uid() and r.active and r.ends_at>now() order by r.created_at desc;
$$;

create or replace function public.convoy_snapshot(p_ride bigint)
returns table(user_id uuid,username text,scooter text,role text,latitude double precision,longitude double precision,speed_mps real,age_seconds integer,distance_from_leader_m double precision)
language sql stable security definer set search_path=public as $$
 with leader as(select p.latitude,p.longitude from group_ride_presence p join group_ride_members m on m.ride_id=p.ride_id and m.user_id=p.user_id where p.ride_id=p_ride and m.role='leader' limit 1)
 select m.user_id,pr.username,pr.scooter,m.role,p.latitude,p.longitude,coalesce(p.speed_mps,0),coalesce(extract(epoch from now()-p.updated_at)::integer,999),
 case when l.latitude is null then 0 else 6371000*acos(least(1,greatest(-1,cos(radians(l.latitude))*cos(radians(p.latitude))*cos(radians(p.longitude)-radians(l.longitude))+sin(radians(l.latitude))*sin(radians(p.latitude))))) end
 from group_ride_members m join profiles pr on pr.id=m.user_id left join group_ride_presence p on p.ride_id=m.ride_id and p.user_id=m.user_id left join leader l on true
 where m.ride_id=p_ride and public.is_group_ride_member(p_ride) order by case when m.role='leader' then 0 else 1 end,pr.username;
$$;

create or replace function public.send_convoy_alert(p_ride bigint,p_type text,p_lat double precision default null,p_lon double precision default null)
returns bigint language plpgsql security definer set search_path=public as $$
declare aid bigint;label text;
begin
 if not public.is_group_ride_member(p_ride) then raise exception 'Join the convoy first'; end if;
 label=case p_type when 'regroup' then 'Regroup requested' when 'fuel' then 'Fuel stop needed' when 'mechanical' then 'Mechanical problem' when 'hazard' then 'Road hazard ahead' when 'police' then 'Police ahead' when 'pull_over' then 'Pull over safely' when 'ready' then 'Rider ready' else null end;
 if label is null then raise exception 'Invalid convoy alert'; end if;
 insert into convoy_alerts(ride_id,sender_id,alert_type,message,latitude,longitude) values(p_ride,auth.uid(),p_type,label,p_lat,p_lon) returning id into aid;return aid;
end $$;

create or replace function public.convoy_recent_alerts(p_ride bigint)
returns table(id bigint,sender_id uuid,username text,alert_type text,message text,latitude double precision,longitude double precision,created_at timestamptz)
language sql stable security definer set search_path=public as $$
 select a.id,a.sender_id,p.username,a.alert_type,a.message,a.latitude,a.longitude,a.created_at from convoy_alerts a join profiles p on p.id=a.sender_id
 where a.ride_id=p_ride and public.is_group_ride_member(p_ride) and a.created_at>now()-interval '30 minutes' order by a.created_at desc limit 30;
$$;

create or replace function public.leave_convoy(p_ride bigint)
returns void language plpgsql security definer set search_path=public as $$
begin
 if exists(select 1 from group_rides where id=p_ride and owner_id=auth.uid()) then update group_rides set active=false,updated_at=now() where id=p_ride;
 else delete from group_ride_members where ride_id=p_ride and user_id=auth.uid(); end if;
end $$;

revoke all on function public.create_convoy(text,text,boolean) from public;
revoke all on function public.convoy_snapshot(bigint) from public;
revoke all on function public.send_convoy_alert(bigint,text,double precision,double precision) from public;
revoke all on function public.convoy_recent_alerts(bigint) from public;
revoke all on function public.leave_convoy(bigint) from public;
grant execute on function public.create_convoy(text,text,boolean) to authenticated;
grant execute on function public.convoy_snapshot(bigint) to authenticated;
grant execute on function public.send_convoy_alert(bigint,text,double precision,double precision) to authenticated;
grant execute on function public.convoy_recent_alerts(bigint) to authenticated;
grant execute on function public.leave_convoy(bigint) to authenticated;
grant select,insert on public.convoy_alerts to authenticated;
