-- RiderLink initial schema. Run once in Supabase Dashboard > SQL Editor.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null check (char_length(username) between 3 and 30),
  scooter text not null default 'Scooter' check (char_length(scooter) <= 60),
  privacy text not null default 'invisible' check (privacy in ('invisible','nearby')),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create unique index if not exists profiles_username_lower on public.profiles(lower(username));

create table if not exists public.rider_presence (
  user_id uuid primary key references auth.users(id) on delete cascade,
  latitude double precision not null check (latitude between -90 and 90),
  longitude double precision not null check (longitude between -180 and 180),
  accuracy real not null default 0,
  privacy text not null default 'invisible' check (privacy in ('invisible','nearby')),
  updated_at timestamptz not null default now()
);

create table if not exists public.sos_alerts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  latitude double precision not null, longitude double precision not null,
  message text not null default 'Rider needs assistance' check (char_length(message) <= 240),
  active boolean not null default true, created_at timestamptz not null default now()
);
create index if not exists sos_active_created on public.sos_alerts(active, created_at desc);

alter table public.profiles enable row level security;
alter table public.rider_presence enable row level security;
alter table public.sos_alerts enable row level security;

drop policy if exists "profile own write" on public.profiles;
create policy "profile own write" on public.profiles for all to authenticated using (id = auth.uid()) with check (id = auth.uid());
drop policy if exists "profiles readable by riders" on public.profiles;
create policy "profiles readable by riders" on public.profiles for select to authenticated using (true);
drop policy if exists "presence own write" on public.rider_presence;
create policy "presence own write" on public.rider_presence for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists "sos own insert" on public.sos_alerts;
create policy "sos own insert" on public.sos_alerts for insert to authenticated with check (user_id = auth.uid());
drop policy if exists "sos own update" on public.sos_alerts;
create policy "sos own update" on public.sos_alerts for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

-- Returns only fresh, opted-in riders within the radius. Coordinates are rounded to ~110m for public privacy.
create or replace function public.nearby_riders(p_lat double precision, p_lon double precision, p_radius_km double precision default 25)
returns table(user_id uuid, username text, scooter text, latitude double precision, longitude double precision, distance_km double precision)
language sql stable security definer set search_path = public as $$
  select rp.user_id, p.username, p.scooter, round(rp.latitude::numeric,3)::double precision,
    round(rp.longitude::numeric,3)::double precision,
    6371 * acos(least(1, greatest(-1, cos(radians(p_lat))*cos(radians(rp.latitude))*cos(radians(rp.longitude)-radians(p_lon))+sin(radians(p_lat))*sin(radians(rp.latitude)))))
  from public.rider_presence rp join public.profiles p on p.id=rp.user_id
  where rp.privacy='nearby' and rp.updated_at > now()-interval '2 minutes' and rp.user_id <> auth.uid()
    and 6371 * acos(least(1, greatest(-1, cos(radians(p_lat))*cos(radians(rp.latitude))*cos(radians(rp.longitude)-radians(p_lon))+sin(radians(p_lat))*sin(radians(rp.latitude))))) <= least(p_radius_km,25)
  order by 6 limit 100;
$$;
revoke all on function public.nearby_riders(double precision,double precision,double precision) from public;
grant execute on function public.nearby_riders(double precision,double precision,double precision) to authenticated;

-- Active SOS alerts are exact-location safety events and expire after four hours.
create or replace function public.nearby_sos(p_lat double precision, p_lon double precision, p_radius_km double precision default 40)
returns table(id bigint, user_id uuid, username text, latitude double precision, longitude double precision, message text, created_at timestamptz)
language sql stable security definer set search_path = public as $$
  select s.id,s.user_id,p.username,s.latitude,s.longitude,s.message,s.created_at
  from public.sos_alerts s join public.profiles p on p.id=s.user_id
  where s.active and s.created_at > now()-interval '4 hours' and s.user_id <> auth.uid()
    and 6371 * acos(least(1, greatest(-1, cos(radians(p_lat))*cos(radians(s.latitude))*cos(radians(s.longitude)-radians(p_lon))+sin(radians(p_lat))*sin(radians(s.latitude))))) <= least(p_radius_km,40)
  order by s.created_at desc limit 50;
$$;
revoke all on function public.nearby_sos(double precision,double precision,double precision) from public;
grant execute on function public.nearby_sos(double precision,double precision,double precision) to authenticated;
