-- RiderLink v8.5: temporary Ride Beacons, Waves, and activity inbox.
-- Safe to run more than once in the Supabase SQL editor.

create table if not exists public.ride_beacons (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  kind text not null check (kind in ('cruising','ride','meetup','mechanical')),
  note text not null default '' check (char_length(note) <= 120),
  latitude double precision not null check (latitude between -90 and 90),
  longitude double precision not null check (longitude between -180 and 180),
  expires_at timestamptz not null default (now() + interval '2 hours'),
  updated_at timestamptz not null default now()
);

alter table public.ride_beacons enable row level security;
drop policy if exists "beacon owner write" on public.ride_beacons;
create policy "beacon owner write" on public.ride_beacons for all to authenticated
using (auth.uid() = user_id) with check (auth.uid() = user_id);

create or replace function public.refresh_ride_beacon_expiry()
returns trigger language plpgsql security invoker set search_path = public as $$
begin
  new.updated_at := now();
  new.expires_at := now() + case when new.kind = 'mechanical' then interval '1 hour' else interval '2 hours' end;
  return new;
end $$;
drop trigger if exists ride_beacon_refresh on public.ride_beacons;
create trigger ride_beacon_refresh before insert or update on public.ride_beacons
for each row execute function public.refresh_ride_beacon_expiry();

drop function if exists public.nearby_ride_beacons(double precision,double precision,double precision);
create function public.nearby_ride_beacons(p_lat double precision,p_lon double precision,p_radius_km double precision default 40)
returns table(user_id uuid,username text,scooter text,kind text,note text,latitude double precision,longitude double precision,distance_km double precision,expires_at timestamptz)
language sql stable security definer set search_path = public as $$
  select b.user_id,p.username,p.scooter,b.kind,b.note,
    -- About a city block of coordinate blurring. Exact GPS stays out of discovery results.
    round(b.latitude::numeric,3)::double precision,round(b.longitude::numeric,3)::double precision,
    (6371 * acos(least(1,greatest(-1,cos(radians(p_lat))*cos(radians(b.latitude))*cos(radians(b.longitude)-radians(p_lon))+sin(radians(p_lat))*sin(radians(b.latitude))))))::double precision,
    b.expires_at
  from public.ride_beacons b join public.profiles p on p.id=b.user_id
  where b.expires_at > now() and b.user_id <> auth.uid()
    and 6371 * acos(least(1,greatest(-1,cos(radians(p_lat))*cos(radians(b.latitude))*cos(radians(b.longitude)-radians(p_lon))+sin(radians(p_lat))*sin(radians(b.latitude))))) <= least(greatest(p_radius_km,1),80)
  order by 8;
$$;

create table if not exists public.rider_waves (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  recipient_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  read_at timestamptz,
  check (sender_id <> recipient_id)
);
create index if not exists rider_waves_recipient_idx on public.rider_waves(recipient_id,created_at desc);
alter table public.rider_waves enable row level security;
drop policy if exists "wave participants read" on public.rider_waves;
create policy "wave participants read" on public.rider_waves for select to authenticated using (auth.uid() in (sender_id,recipient_id));

create or replace function public.send_rider_wave(p_recipient uuid)
returns bigint language plpgsql security definer set search_path=public as $$
declare result bigint;
begin
  if auth.uid() is null or p_recipient=auth.uid() then raise exception 'Invalid rider'; end if;
  if not exists(select 1 from public.profiles where id=p_recipient) then raise exception 'Rider not found'; end if;
  if exists(select 1 from public.rider_waves where sender_id=auth.uid() and recipient_id=p_recipient and created_at>now()-interval '10 minutes') then raise exception 'You already waved recently'; end if;
  insert into public.rider_waves(sender_id,recipient_id) values(auth.uid(),p_recipient) returning id into result;
  return result;
end $$;

drop function if exists public.my_rider_activity();
create function public.my_rider_activity()
returns table(id bigint,sender_id uuid,username text,scooter text,created_at timestamptz,is_unread boolean)
language sql stable security definer set search_path=public as $$
  select w.id,w.sender_id,p.username,p.scooter,w.created_at,(w.read_at is null)
  from public.rider_waves w join public.profiles p on p.id=w.sender_id
  where w.recipient_id=auth.uid() order by w.created_at desc limit 50;
$$;

create or replace function public.mark_rider_activity_read()
returns void language sql security definer set search_path=public as $$
  update public.rider_waves set read_at=coalesce(read_at,now()) where recipient_id=auth.uid() and read_at is null;
$$;

revoke all on function public.nearby_ride_beacons(double precision,double precision,double precision) from public;
revoke all on function public.send_rider_wave(uuid) from public;
revoke all on function public.my_rider_activity() from public;
revoke all on function public.mark_rider_activity_read() from public;
grant execute on function public.nearby_ride_beacons(double precision,double precision,double precision) to authenticated;
grant execute on function public.send_rider_wave(uuid) to authenticated;
grant execute on function public.my_rider_activity() to authenticated;
grant execute on function public.mark_rider_activity_read() to authenticated;
grant select,insert,update,delete on public.ride_beacons to authenticated;
grant select on public.rider_waves to authenticated;
