-- RiderLink Play Billing v9.2. Run after riderlink_membership_v86.sql.
-- Safe to run repeatedly. Purchase verification is performed by the
-- verify-play-purchase Edge Function using the service-role key.
create extension if not exists pgcrypto with schema extensions;

alter table public.riderlink_entitlements add column if not exists pro_access boolean not null default false;
alter table public.riderlink_entitlements add column if not exists entitlement_source text not null default 'code';
alter table public.riderlink_entitlements add column if not exists play_product_id text;
alter table public.riderlink_entitlements add column if not exists play_purchase_hash text;
alter table public.riderlink_entitlements add column if not exists auto_renewing boolean not null default false;
alter table public.riderlink_entitlements drop constraint if exists riderlink_entitlements_tier_check;
alter table public.riderlink_entitlements add constraint riderlink_entitlements_tier_check
  check(tier in('developer','founder_lifetime','founder_price','complimentary','play_founder','play_pro','play_plus'));

-- Existing permanent/code memberships keep Pro access during the store transition.
update public.riderlink_entitlements set pro_access=true
where tier in('developer','founder_lifetime') and not pro_access;

create table if not exists public.riderlink_billing_config(
  singleton boolean primary key default true check(singleton),
  founder_limit integer not null default 1000 check(founder_limit between 1 and 100000),
  founder_claimed integer not null default 0 check(founder_claimed>=0 and founder_claimed<=founder_limit),
  updated_at timestamptz not null default now()
);
insert into public.riderlink_billing_config(singleton) values(true) on conflict(singleton) do nothing;

create table if not exists public.riderlink_play_purchases(
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id text not null check(product_id in('rider_pro_founder_lifetime','rider_pro_lifetime','riderlink_plus_monthly')),
  purchase_token_hash text not null unique,
  order_id text,
  purchase_state text not null default 'active' check(purchase_state in('active','grace','expired','revoked','refunded')),
  expires_at timestamptz,
  auto_renewing boolean not null default false,
  founder_position integer unique check(founder_position between 1 and 1000),
  verified_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id,product_id)
);

alter table public.riderlink_billing_config enable row level security;
alter table public.riderlink_play_purchases enable row level security;
revoke all on public.riderlink_billing_config from public,anon,authenticated;
revoke all on public.riderlink_play_purchases from public,anon,authenticated;

create or replace function public.riderlink_billing_status()
returns table(founder_limit integer,founder_claimed integer,founder_remaining integer,founder_open boolean)
language sql stable security definer set search_path=public as $$
  select c.founder_limit,c.founder_claimed,greatest(0,c.founder_limit-c.founder_claimed),c.founder_claimed<c.founder_limit
  from public.riderlink_billing_config c where c.singleton;
$$;

create or replace function public.my_riderlink_access()
returns table(tier text,pro_access boolean,plus_access boolean,founder_price_eligible boolean,expires_at timestamptz,is_admin boolean)
language sql stable security definer set search_path=public as $$
  select coalesce(e.tier,'free'),coalesce(e.pro_access,false),
    coalesce(e.plus_access and (e.expires_at is null or e.expires_at>now()),false),
    coalesce(e.founder_price_eligible,false),e.expires_at,
    exists(select 1 from public.riderlink_admins a where a.user_id=auth.uid())
  from(select auth.uid() user_id)u left join public.riderlink_entitlements e on e.user_id=u.user_id;
$$;

-- Only the service role used by the verification Edge Function may call this.
create or replace function public.grant_verified_play_purchase(
  p_user uuid,p_product text,p_token_hash text,p_order_id text default null,
  p_expires_at timestamptz default null,p_auto_renewing boolean default false,p_state text default 'active')
returns jsonb language plpgsql security definer set search_path=public as $$
declare cfg public.riderlink_billing_config%rowtype;purchase_id bigint;position integer;existing public.riderlink_play_purchases%rowtype;
begin
  if p_user is null or not exists(select 1 from auth.users where id=p_user) then raise exception 'Unknown RiderLink user';end if;
  if p_product not in('rider_pro_founder_lifetime','rider_pro_lifetime','riderlink_plus_monthly') then raise exception 'Unknown Play product';end if;
  if p_token_hash is null or length(p_token_hash)<>64 then raise exception 'Invalid purchase token hash';end if;
  select * into existing from public.riderlink_play_purchases where purchase_token_hash=p_token_hash;
  if existing.id is not null and(existing.user_id<>p_user or existing.product_id<>p_product)then raise exception 'Purchase token already belongs to another account';end if;

  if p_product='rider_pro_founder_lifetime' and existing.id is null then
    select * into cfg from public.riderlink_billing_config where singleton for update;
    if cfg.founder_claimed>=cfg.founder_limit then raise exception 'The Founding 1,000 offer has sold out';end if;
    position=cfg.founder_claimed+1;
    update public.riderlink_billing_config set founder_claimed=position,updated_at=now() where singleton;
  else position=existing.founder_position;end if;

  insert into public.riderlink_play_purchases(user_id,product_id,purchase_token_hash,order_id,purchase_state,expires_at,auto_renewing,founder_position)
  values(p_user,p_product,p_token_hash,p_order_id,p_state,p_expires_at,p_auto_renewing,position)
  on conflict(user_id,product_id)do update set purchase_token_hash=excluded.purchase_token_hash,
    order_id=excluded.order_id,purchase_state=excluded.purchase_state,
    expires_at=excluded.expires_at,auto_renewing=excluded.auto_renewing,updated_at=now()
  returning id into purchase_id;

  insert into public.riderlink_entitlements(user_id,tier,pro_access,plus_access,founder_price_eligible,expires_at,
    entitlement_source,play_product_id,play_purchase_hash,auto_renewing,updated_at)
  values(p_user,case p_product when'rider_pro_founder_lifetime'then'play_founder'when'rider_pro_lifetime'then'play_pro'else'play_plus'end,
    p_product<>'riderlink_plus_monthly',p_product in('rider_pro_founder_lifetime','riderlink_plus_monthly'),false,
    case when p_product='riderlink_plus_monthly'then p_expires_at else null end,'google_play',p_product,p_token_hash,p_auto_renewing,now())
  on conflict(user_id)do update set
    tier=case when riderlink_entitlements.tier='developer'then'developer'when riderlink_entitlements.tier in('founder_lifetime','play_founder')then riderlink_entitlements.tier else excluded.tier end,
    pro_access=riderlink_entitlements.pro_access or excluded.pro_access,
    plus_access=riderlink_entitlements.plus_access or excluded.plus_access,
    expires_at=case when riderlink_entitlements.tier in('developer','founder_lifetime','play_founder')then null when excluded.plus_access then excluded.expires_at else riderlink_entitlements.expires_at end,
    entitlement_source=case when riderlink_entitlements.tier='developer'then riderlink_entitlements.entitlement_source else excluded.entitlement_source end,
    play_product_id=excluded.play_product_id,play_purchase_hash=excluded.play_purchase_hash,
    auto_renewing=excluded.auto_renewing,updated_at=now();
  return jsonb_build_object('purchase_id',purchase_id,'founder_position',position,'product_id',p_product);
end $$;

revoke all on function public.riderlink_billing_status() from public;
revoke all on function public.my_riderlink_access() from public;
revoke all on function public.grant_verified_play_purchase(uuid,text,text,text,timestamptz,boolean,text) from public,anon,authenticated;
grant execute on function public.riderlink_billing_status() to authenticated;
grant execute on function public.my_riderlink_access() to authenticated;
grant execute on function public.grant_verified_play_purchase(uuid,text,text,text,timestamptz,boolean,text) to service_role;
