-- RiderLink initial schema. Run once in Supabase Dashboard > SQL Editor.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null check (char_length(username) between 3 and 30),
  scooter text not null default 'Scooter' check (char_length(scooter) <= 60),
  privacy text not null default 'invisible' check (privacy in ('invisible','nearby')),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create unique index if not exists profiles_username_lower on public.profiles(lower(username));

create table if not exists public.rider_presence (
  user_id uuid primary key references auth.users(id) on delete cascade,
  latitude double precision not null check (latitude between -90 and 90),
  longitude double precision not null check (longitude between -180 and 180),
  accuracy real not null default 0,
  privacy text not null default 'invisible' check (privacy in ('invisible','nearby')),
  updated_at timestamptz not null default now()
);

create table if not exists public.sos_alerts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  latitude double precision not null, longitude double precision not null,
  message text not null default 'Rider needs assistance' check (char_length(message) <= 240),
  active boolean not null default true, created_at timestamptz not null default now()
);
create index if not exists sos_active_created on public.sos_alerts(active, created_at desc);

alter table public.profiles enable row level security;
alter table public.rider_presence enable row level security;
alter table public.sos_alerts enable row level security;

drop policy if exists "profile own write" on public.profiles;
create policy "profile own write" on public.profiles for all to authenticated using (id = auth.uid()) with check (id = auth.uid());
drop policy if exists "profiles readable by riders" on public.profiles;
create policy "profiles readable by riders" on public.profiles for select to authenticated using (true);
drop policy if exists "presence own write" on public.rider_presence;
create policy "presence own write" on public.rider_presence for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists "sos own insert" on public.sos_alerts;
create policy "sos own insert" on public.sos_alerts for insert to authenticated with check (user_id = auth.uid());
drop policy if exists "sos own update" on public.sos_alerts;
create policy "sos own update" on public.sos_alerts for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

-- Returns only fresh, opted-in riders within the radius. Coordinates are rounded to ~110m for public privacy.
create or replace function public.nearby_riders(p_lat double precision, p_lon double precision, p_radius_km double precision default 25)
returns table(user_id uuid, username text, scooter text, latitude double precision, longitude double precision, distance_km double precision)
language sql stable security definer set search_path = public as $$
  select rp.user_id, p.username, p.scooter, round(rp.latitude::numeric,3)::double precision,
    round(rp.longitude::numeric,3)::double precision,
    6371 * acos(least(1, greatest(-1, cos(radians(p_lat))*cos(radians(rp.latitude))*cos(radians(rp.longitude)-radians(p_lon))+sin(radians(p_lat))*sin(radians(rp.latitude)))))
  from public.rider_presence rp join public.profiles p on p.id=rp.user_id
  where rp.privacy='nearby' and rp.updated_at > now()-interval '2 minutes' and rp.user_id <> auth.uid()
    and 6371 * acos(least(1, greatest(-1, cos(radians(p_lat))*cos(radians(rp.latitude))*cos(radians(rp.longitude)-radians(p_lon))+sin(radians(p_lat))*sin(radians(rp.latitude))))) <= least(p_radius_km,25)
  order by 6 limit 100;
$$;
revoke all on function public.nearby_riders(double precision,double precision,double precision) from public;
grant execute on function public.nearby_riders(double precision,double precision,double precision) to authenticated;

-- Active SOS alerts are exact-location safety events and expire after four hours.
create or replace function public.nearby_sos(p_lat double precision, p_lon double precision, p_radius_km double precision default 40)
returns table(id bigint, user_id uuid, username text, latitude double precision, longitude double precision, message text, created_at timestamptz)
language sql stable security definer set search_path = public as $$
  select s.id,s.user_id,p.username,s.latitude,s.longitude,s.message,s.created_at
  from public.sos_alerts s join public.profiles p on p.id=s.user_id
  where s.active and s.created_at > now()-interval '4 hours' and s.user_id <> auth.uid()
    and 6371 * acos(least(1, greatest(-1, cos(radians(p_lat))*cos(radians(s.latitude))*cos(radians(s.longitude)-radians(p_lon))+sin(radians(p_lat))*sin(radians(s.latitude))))) <= least(p_radius_km,40)
  order by s.created_at desc limit 50;
$$;
revoke all on function public.nearby_sos(double precision,double precision,double precision) from public;
grant execute on function public.nearby_sos(double precision,double precision,double precision) to authenticated;

-- RiderLink 3.0 social migration. Safe to run over the initial schema.
create table if not exists public.friendships (
  id bigint generated by default as identity primary key,
  requester_id uuid not null references public.profiles(id) on delete cascade,
  addressee_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending' check(status in ('pending','accepted','blocked')),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  check(requester_id <> addressee_id)
);
create unique index if not exists friendships_pair_unique on public.friendships(least(requester_id,addressee_id),greatest(requester_id,addressee_id));
create table if not exists public.direct_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  recipient_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check(char_length(body) between 1 and 1000), created_at timestamptz not null default now()
);
create index if not exists direct_messages_people on public.direct_messages(sender_id,recipient_id,created_at);
create table if not exists public.clubs (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references public.profiles(id) on delete cascade,
  name text not null check(char_length(name) between 3 and 50), invite_code text not null unique,
  created_at timestamptz not null default now()
);
create table if not exists public.club_members (
  club_id bigint not null references public.clubs(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'member' check(role in ('owner','moderator','member')),
  joined_at timestamptz not null default now(), primary key(club_id,user_id)
);
create table if not exists public.club_messages (
  id bigint generated by default as identity primary key,
  club_id bigint not null references public.clubs(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check(char_length(body) between 1 and 1000), created_at timestamptz not null default now()
);
create index if not exists club_messages_timeline on public.club_messages(club_id,created_at);
alter table public.friendships enable row level security; alter table public.direct_messages enable row level security;
alter table public.clubs enable row level security; alter table public.club_members enable row level security; alter table public.club_messages enable row level security;
drop policy if exists "friend participants read" on public.friendships;
create policy "friend participants read" on public.friendships for select to authenticated using(auth.uid() in(requester_id,addressee_id));
drop policy if exists "friend request insert" on public.friendships;
create policy "friend request insert" on public.friendships for insert to authenticated with check(requester_id=auth.uid() and status='pending');
drop policy if exists "friend participants update" on public.friendships;
create policy "friend participants update" on public.friendships for update to authenticated using(auth.uid() in(requester_id,addressee_id)) with check(auth.uid() in(requester_id,addressee_id));
drop policy if exists "dm participants read" on public.direct_messages;
create policy "dm participants read" on public.direct_messages for select to authenticated using(auth.uid() in(sender_id,recipient_id));
drop policy if exists "dm sender insert" on public.direct_messages;
create policy "dm sender insert" on public.direct_messages for insert to authenticated with check(sender_id=auth.uid() and exists(select 1 from public.friendships f where f.status='accepted' and ((f.requester_id=sender_id and f.addressee_id=recipient_id) or (f.addressee_id=sender_id and f.requester_id=recipient_id))));

create or replace function public.is_club_member(p_club bigint) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from club_members where club_id=p_club and user_id=auth.uid())$$;
revoke all on function public.is_club_member(bigint) from public; grant execute on function public.is_club_member(bigint) to authenticated;
drop policy if exists "member clubs read" on public.clubs; create policy "member clubs read" on public.clubs for select to authenticated using(public.is_club_member(id));
drop policy if exists "members read" on public.club_members; create policy "members read" on public.club_members for select to authenticated using(public.is_club_member(club_id));
drop policy if exists "club chat read" on public.club_messages; create policy "club chat read" on public.club_messages for select to authenticated using(public.is_club_member(club_id));
drop policy if exists "club chat insert" on public.club_messages; create policy "club chat insert" on public.club_messages for insert to authenticated with check(sender_id=auth.uid() and public.is_club_member(club_id));

create or replace function public.my_friends() returns table(id uuid,username text,scooter text)
language sql stable security definer set search_path=public as $$
 select p.id,p.username,p.scooter from friendships f join profiles p on p.id=case when f.requester_id=auth.uid() then f.addressee_id else f.requester_id end where f.status='accepted' and auth.uid() in(f.requester_id,f.addressee_id) order by p.username;
$$;
create or replace function public.my_clubs() returns table(id bigint,name text,invite_code text,role text)
language sql stable security definer set search_path=public as $$select c.id,c.name,c.invite_code,m.role from club_members m join clubs c on c.id=m.club_id where m.user_id=auth.uid() order by c.name$$;
create or replace function public.create_club(p_name text) returns bigint language plpgsql security definer set search_path=public as $$declare new_id bigint;begin if char_length(trim(p_name)) not between 3 and 50 then raise exception 'Club name must be 3-50 characters';end if;insert into clubs(owner_id,name,invite_code) values(auth.uid(),trim(p_name),upper(substr(md5(random()::text||clock_timestamp()::text),1,8))) returning id into new_id;insert into club_members(club_id,user_id,role) values(new_id,auth.uid(),'owner');return new_id;end$$;
create or replace function public.join_club(p_code text) returns bigint language plpgsql security definer set search_path=public as $$declare found_id bigint;begin select id into found_id from clubs where invite_code=upper(trim(p_code));if found_id is null then raise exception 'Invite code not found';end if;insert into club_members(club_id,user_id) values(found_id,auth.uid()) on conflict do nothing;return found_id;end$$;
revoke all on function public.my_friends() from public; revoke all on function public.my_clubs() from public; revoke all on function public.create_club(text) from public; revoke all on function public.join_club(text) from public;
grant execute on function public.my_friends() to authenticated; grant execute on function public.my_clubs() to authenticated; grant execute on function public.create_club(text) to authenticated; grant execute on function public.join_club(text) to authenticated;

-- RiderLink 3.1 community Flock/ALPR camera reports.
create table if not exists public.community_hazards (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null references public.profiles(id) on delete cascade,
  type text not null check(type in ('flock_camera')),
  latitude double precision not null check(latitude between -90 and 90),
  longitude double precision not null check(longitude between -180 and 180),
  active boolean not null default true, created_at timestamptz not null default now()
);
create index if not exists community_hazards_active on public.community_hazards(type,active,created_at desc);
alter table public.community_hazards enable row level security;
drop policy if exists "community hazards own insert" on public.community_hazards;
create policy "community hazards own insert" on public.community_hazards for insert to authenticated with check(reporter_id=auth.uid());
drop policy if exists "community hazards own update" on public.community_hazards;
create policy "community hazards own update" on public.community_hazards for update to authenticated using(reporter_id=auth.uid()) with check(reporter_id=auth.uid());
create or replace function public.nearby_community_hazards(p_lat double precision,p_lon double precision,p_radius_km double precision default 50)
returns table(id bigint,type text,latitude double precision,longitude double precision,created_at timestamptz)
language sql stable security definer set search_path=public as $$
 select h.id,h.type,h.latitude,h.longitude,h.created_at from community_hazards h
 where h.active and h.created_at>now()-interval '180 days'
 and 6371*acos(least(1,greatest(-1,cos(radians(p_lat))*cos(radians(h.latitude))*cos(radians(h.longitude)-radians(p_lon))+sin(radians(p_lat))*sin(radians(h.latitude)))))<=least(p_radius_km,50)
 order by h.created_at desc limit 500;
$$;
revoke all on function public.nearby_community_hazards(double precision,double precision,double precision) from public;
grant execute on function public.nearby_community_hazards(double precision,double precision,double precision) to authenticated;

-- RiderLink 4.0 identity + scooter garage migration. Safe over all earlier versions.
alter table public.profiles add column if not exists avatar_config jsonb not null default '{}'::jsonb;
alter table public.profiles add column if not exists avatar_3d_url text not null default '' check(char_length(avatar_3d_url)<=2000);
alter table public.profiles add column if not exists scooter_make text not null default '' check(char_length(scooter_make)<=60);
alter table public.profiles add column if not exists scooter_model text not null default '' check(char_length(scooter_model)<=80);
alter table public.profiles add column if not exists scooter_upgrades text not null default '' check(char_length(scooter_upgrades)<=1000);

drop function if exists public.my_friends();
create function public.my_friends()
returns table(id uuid,username text,scooter text,scooter_make text,scooter_model text,scooter_upgrades text,avatar_config jsonb,avatar_3d_url text)
language sql stable security definer set search_path=public as $$
 select p.id,p.username,p.scooter,p.scooter_make,p.scooter_model,p.scooter_upgrades,p.avatar_config,p.avatar_3d_url
 from friendships f join profiles p on p.id=case when f.requester_id=auth.uid() then f.addressee_id else f.requester_id end
 where f.status='accepted' and auth.uid() in(f.requester_id,f.addressee_id) order by p.username;
$$;
revoke all on function public.my_friends() from public;
grant execute on function public.my_friends() to authenticated;
