plugins { id 'com.android.application' }

android {
    namespace 'com.stankhouse.scooterspeedometer'
    compileSdk 35

    defaultConfig {
        applicationId 'com.stankhouse.scooterspeedometer'
        minSdk 23
        targetSdk 35
        versionCode 30
        versionName '4.8'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
