package com.stankhouse.scooterspeedometer;

import android.Manifest;import android.app.Activity;import android.app.AlertDialog;import android.content.pm.PackageManager;import android.graphics.Color;import android.location.Location;import android.location.LocationListener;import android.location.LocationManager;import android.os.Bundle;import android.os.Handler;import android.os.Looper;import android.view.Gravity;import android.view.View;import android.widget.Button;import android.widget.EditText;import android.widget.LinearLayout;import android.widget.ScrollView;import android.widget.TextView;import android.widget.Toast;import org.json.JSONArray;import org.json.JSONObject;import java.util.Locale;

/** Temporary RiderLink group sessions with join codes and live member status. */
public class GroupRideActivity extends Activity implements LocationListener{
    private RiderLinkClient client;private LinearLayout content;private LocationManager locations;private Location fix;private long activeRide;private final Handler handler=new Handler(Looper.getMainLooper());private final Runnable refresh=new Runnable(){public void run(){load();if(activeRide>0&&fix!=null)client.updateGroupRideLocation(activeRide,fix.getLatitude(),fix.getLongitude(),fix.getSpeed(),(o,m,b)->{});handler.postDelayed(this,10000);}};
    @Override protected void onCreate(Bundle b){super.onCreate(b);Fullscreen.apply(this);client=new RiderLinkClient(this);locations=(LocationManager)getSystemService(LOCATION_SERVICE);build();startGps();handler.post(refresh);}
    private void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackground(UiKit.screenBackground(this));LinearLayout head=UiKit.header(this,"⌖","Group rides","TEMPORARY LIVE RIDER SESSIONS");Button close=UiKit.iconButton(this,"×","Close",UiKit.SURFACE_HIGH);close.setOnClickListener(v->finish());head.addView(close,new LinearLayout.LayoutParams(dp(92),dp(48)));root.addView(head,new LinearLayout.LayoutParams(-1,dp(76)));LinearLayout actions=new LinearLayout(this);actions.setPadding(dp(12),dp(4),dp(12),dp(8));Button create=UiKit.iconButton(this,"+","Create",UiKit.SURFACE_ACTIVE),join=UiKit.iconButton(this,"→","Join code",UiKit.SURFACE_HIGH);actions.addView(create,new LinearLayout.LayoutParams(0,dp(52),1));actions.addView(join,new LinearLayout.LayoutParams(0,dp(52),1));root.addView(actions);ScrollView s=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(14),0,dp(14),dp(20));s.addView(content);root.addView(s,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);create.setOnClickListener(v->createDialog());join.setOnClickListener(v->joinDialog());}
    private void load(){client.myActiveGroupRides((ok,m,body)->{if(!ok){show(m);return;}content.removeAllViews();content.addView(UiKit.section(this,"⌖","Active rides"));try{JSONArray rides=new JSONArray(body);if(rides.length()==0){show("No active group ride. Create one or enter an invite code.");activeRide=0;}for(int i=0;i<rides.length();i++){JSONObject r=rides.getJSONObject(i);long id=r.getLong("id");if(i==0)activeRide=id;row(r.optString("name","Group ride"),r.optString("destination","Open destination")+"\nCode: "+r.optString("invite_code")+" • "+r.optInt("member_count",1)+" riders",id);}}catch(Exception e){show(e.getMessage());}});}
    private void row(String name,String detail,long id){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(14),dp(8),dp(8),dp(8));UiKit.card(row);TextView t=UiKit.text(this,name+"\n"+detail,15,UiKit.TEXT,true);row.addView(t,new LinearLayout.LayoutParams(0,dp(78),1));Button live=UiKit.iconButton(this,"◎","Live",UiKit.SURFACE_ACTIVE);live.setOnClickListener(v->{activeRide=id;Toast.makeText(this,"Live sharing enabled for this ride",Toast.LENGTH_LONG).show();});row.addView(live,new LinearLayout.LayoutParams(dp(92),dp(48)));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(94));lp.setMargins(0,0,0,dp(9));content.addView(row,lp);}
    private void createDialog(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(16),0,dp(16),0);EditText name=field("Ride name"),dest=field("Destination / meeting point");box.addView(name);box.addView(dest);new AlertDialog.Builder(this).setTitle("Create group ride").setView(box).setPositiveButton("Create",(d,w)->client.createGroupRide(name.getText().toString().trim(),dest.getText().toString().trim(),(ok,m,b)->{toast(ok?"Group ride created":m);load();})).setNegativeButton("Cancel",null).show();}
    private void joinDialog(){EditText code=field("8-character invite code");new AlertDialog.Builder(this).setTitle("Join group ride").setView(code).setPositiveButton("Join",(d,w)->client.joinGroupRide(code.getText().toString().trim(),(ok,m,b)->{toast(ok?"Joined group ride":m);load();})).setNegativeButton("Cancel",null).show();}
    private EditText field(String hint){EditText e=new EditText(this);e.setHint(hint);UiKit.field(e);return e;}private void show(String s){content.removeAllViews();TextView t=UiKit.text(this,s,14,UiKit.MUTED,false);t.setGravity(Gravity.CENTER);content.addView(t,new LinearLayout.LayoutParams(-1,dp(100)));}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}private int dp(int v){return UiKit.dp(this,v);}
    private void startGps(){if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED)return;try{locations.requestLocationUpdates(LocationManager.GPS_PROVIDER,1500,2,this);}catch(Exception ignored){}}@Override public void onLocationChanged(Location l){fix=l;}@Override public void onProviderEnabled(String p){}@Override public void onProviderDisabled(String p){}@Override public void onStatusChanged(String p,int s,Bundle b){}
    @Override protected void onDestroy(){handler.removeCallbacks(refresh);try{locations.removeUpdates(this);}catch(Exception ignored){}if(activeRide>0&&fix!=null)client.updateGroupRideLocation(activeRide,fix.getLatitude(),fix.getLongitude(),0,(o,m,b)->{});client.shutdown();super.onDestroy();}
}
