package com.stankhouse.scooterspeedometer;

import android.app.Activity;import android.app.AlertDialog;import android.content.SharedPreferences;import android.graphics.Color;import android.os.Bundle;import android.text.InputType;import android.view.Gravity;import android.view.View;import android.widget.Button;import android.widget.EditText;import android.widget.LinearLayout;import android.widget.ScrollView;import android.widget.TextView;import android.widget.Toast;
import java.util.Locale;

/** Mileage-aware service garage for common scooter wear items. */
public class MaintenanceGarageActivity extends Activity {
    private SharedPreferences p;private LinearLayout content;private double miles;
    private static final String[][] ITEMS={{"engine_oil","Engine oil","500"},{"gear_oil","Gear oil","1500"},{"valves","Valve adjustment","1000"},{"belt","CVT belt","3000"},{"rollers","Rollers / sliders","2500"},{"brakes","Brakes","2000"},{"tires","Tires","4000"}};
    @Override protected void onCreate(Bundle b){super.onCreate(b);Fullscreen.apply(this);p=getSharedPreferences("maintenance_garage",MODE_PRIVATE);miles=getIntent().getDoubleExtra("miles",0);build();}
    private void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackground(UiKit.screenBackground(this));LinearLayout head=UiKit.header(this,"◆","Maintenance garage",String.format(Locale.US,"RECORDED ODOMETER • %.1f MI",miles));Button close=UiKit.iconButton(this,"×","Close",UiKit.SURFACE_HIGH);close.setOnClickListener(v->finish());head.addView(close,new LinearLayout.LayoutParams(dp(92),dp(48)));root.addView(head,new LinearLayout.LayoutParams(-1,dp(76)));ScrollView s=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(14),0,dp(14),dp(18));s.addView(content);root.addView(s,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);render();}
    private void render(){content.removeAllViews();content.addView(UiKit.section(this,"◇","Service schedule"));for(String[] item:ITEMS){double last=Double.longBitsToDouble(p.getLong(item[0]+"_last",Double.doubleToLongBits(0))),interval=Double.longBitsToDouble(p.getLong(item[0]+"_interval",Double.doubleToLongBits(Double.parseDouble(item[2]))));double due=last+interval,remaining=due-miles;LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(14),dp(7),dp(8),dp(7));UiKit.card(row);TextView info=UiKit.text(this,item[1]+"\n"+(remaining<=0?String.format(Locale.US,"OVERDUE %.0f MI",-remaining):String.format(Locale.US,"Due in %.0f mi • every %.0f mi",remaining,interval)),15,remaining<=0?UiKit.RED:UiKit.TEXT,true);row.addView(info,new LinearLayout.LayoutParams(0,dp(68),1));Button done=UiKit.iconButton(this,"✓","Serviced",UiKit.SURFACE_ACTIVE);done.setOnClickListener(v->{p.edit().putLong(item[0]+"_last",Double.doubleToLongBits(miles)).apply();render();});row.addView(done,new LinearLayout.LayoutParams(dp(112),dp(48)));row.setOnLongClickListener(v->{intervalDialog(item);return true;});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(82));lp.setMargins(0,0,0,dp(9));content.addView(row,lp);}TextView hint=UiKit.text(this,"Hold a service item to change its mileage interval.",12,UiKit.MUTED,false);hint.setGravity(Gravity.CENTER);content.addView(hint,new LinearLayout.LayoutParams(-1,dp(48)));}
    private void intervalDialog(String[] item){EditText e=new EditText(this);e.setHint("Miles between service");e.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);UiKit.field(e);new AlertDialog.Builder(this).setTitle(item[1]+" interval").setView(e).setPositiveButton("Save",(d,w)->{try{double value=Double.parseDouble(e.getText().toString());if(value<25)throw new Exception();p.edit().putLong(item[0]+"_interval",Double.doubleToLongBits(value)).apply();render();}catch(Exception x){Toast.makeText(this,"Enter at least 25 miles",Toast.LENGTH_LONG).show();}}).setNegativeButton("Cancel",null).show();}
    private int dp(int v){return UiKit.dp(this,v);}
}
