package com.stankhouse.scooterspeedometer;

import android.Manifest;import android.app.*;import android.content.pm.PackageManager;import android.location.*;import android.os.*;import android.view.*;import android.widget.*;import org.json.*;import java.util.*;

/** Two-hour, opt-in location sharing for roadside help. Never calls emergency services. */
public final class RescueNetworkActivity extends Activity implements LocationListener{
 private RiderLinkClient client;private LocationManager manager;private Location fix;private LinearLayout body;private TextView status;
 @Override public void onCreate(Bundle b){super.onCreate(b);client=new RiderLinkClient(this);manager=(LocationManager)getSystemService(LOCATION_SERVICE);LinearLayout root=col();root.setPadding(dp(14),dp(10),dp(14),dp(8));root.setBackground(UiKit.screenBackground(this));root.addView(UiKit.header(this,"⚒","RESCUE NETWORK","Tools • fuel • mechanical • trailer"));root.addView(button("‹ Events",this::finish));status=UiKit.text(this,"Waiting for a safe GPS fix…",13,UiKit.CYAN,true);root.addView(status);LinearLayout actions=new LinearLayout(this);actions.addView(button("Request help",this::requestHelp),new LinearLayout.LayoutParams(0,dp(52),1));actions.addView(button("Nearby requests",this::loadNearby),new LinearLayout.LayoutParams(0,dp(52),1));actions.addView(button("My rescue center",this::myCenter),new LinearLayout.LayoutParams(0,dp(52),1));root.addView(actions);body=col();ScrollView scroll=new ScrollView(this);scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));root.addView(UiKit.text(this,"RiderLink Rescue shares the requester's exact location for up to two hours. It is not emergency dispatch. Call 911 for immediate danger.",11,UiKit.MUTED,false));setContentView(root);requestLocation();}
 private void requestLocation(){if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION},71);return;}try{manager.requestLocationUpdates(LocationManager.GPS_PROVIDER,1000,0,this);Location last=manager.getLastKnownLocation(LocationManager.GPS_PROVIDER);if(last!=null)onLocationChanged(last);}catch(SecurityException ignored){}}
 @Override public void onLocationChanged(Location l){if(l.hasAccuracy()&&l.getAccuracy()<120){fix=l;status.setText(String.format(Locale.US,"GPS ready • ±%.0f m",l.getAccuracy()));}}
 private void requestHelp(){if(fix==null){toast("Wait for a GPS fix before sharing a rescue request");return;}String[] needs={"Tools","Fuel","Mechanical","Trailer","Battery","Other"};new AlertDialog.Builder(this).setTitle("What do you need?").setItems(needs,(d,w)->{EditText note=field("Short note: scooter, problem, landmark");new AlertDialog.Builder(this).setTitle("Share exact location for 2 hours?").setMessage("Nearby signed-in riders can see this rescue request and offer help.").setView(note).setNegativeButton("Cancel",null).setPositiveButton("Request help",(x,y)->rpc("request_rider_rescue",obj("p_need",needs[w].toLowerCase(Locale.US),"p_note",note.getText().toString(),"p_lat",fix.getLatitude(),"p_lon",fix.getLongitude(),"p_city",""),(o,m,b)->{toast(o?"Rescue request is live for two hours":m);if(o)myCenter();})).show();}).show();}
 private void loadNearby(){if(fix==null){toast("Wait for a GPS fix");return;}body.removeAllViews();status.setText("Searching within 40 km…");rpc("nearby_rescue_requests",obj("p_lat",fix.getLatitude(),"p_lon",fix.getLongitude(),"p_radius_km",40),(ok,m,b)->{if(!ok){error(m);return;}try{JSONArray a=new JSONArray(b);status.setText(a.length()+" nearby rescue requests");if(a.length()==0)addText("No active nearby requests.");for(int i=0;i<a.length();i++){JSONObject r=a.getJSONObject(i);long id=r.getLong("id");String destination=r.getDouble("latitude")+","+r.getDouble("longitude");addRow(r.optString("need").toUpperCase()+" • "+r.optString("username"),String.format(Locale.US,"%.1f km • %s",r.optDouble("distance_km"),r.optString("note")),v->new AlertDialog.Builder(this).setTitle("Help "+r.optString("username")+"?").setItems(new String[]{"Offer help","Navigate to rider"},(d,w)->{if(w==1)startActivity(new android.content.Intent(this,BuiltInNavigationActivity.class).putExtra("destination",destination));else offer(id);}).show());}}catch(Exception e){error("Unable to read rescue requests");}});}
 private void offer(long request){EditText message=field("What can you bring or do?");new AlertDialog.Builder(this).setTitle("Offer roadside help").setView(message).setNegativeButton("Cancel",null).setPositiveButton("Send offer",(d,w)->rpc("offer_rider_rescue",obj("p_request",request,"p_message",message.getText().toString()),(o,m,b)->toast(o?"Help offer sent":m))).show();}
 private void myCenter(){body.removeAllViews();rpc("my_rescue_center",new JSONObject(),(ok,m,b)->{if(!ok){error(m);return;}try{JSONObject x=new JSONObject(b);JSONArray req=x.optJSONArray("requests"),offers=x.optJSONArray("offers");addText("MY REQUESTS");if(req!=null)for(int i=0;i<req.length();i++){JSONObject r=req.getJSONObject(i);addRow(r.optString("need").toUpperCase(),r.optBoolean("active")?"ACTIVE":"CLOSED",null);}addText("HELP OFFERS");if(offers==null||offers.length()==0)addText("No offers yet.");else for(int i=0;i<offers.length();i++){JSONObject o=offers.getJSONObject(i);long rid=o.getLong("request_id");String helper=o.getString("helper_id");addRow(o.optString("username")+" • "+o.optString("status"),o.optString("message"),v->new AlertDialog.Builder(this).setTitle(o.optString("username")).setItems(new String[]{"Accept","Decline","Mark help completed"},(d,w)->{String state=new String[]{"accepted","declined","completed"}[w];rpc("update_rescue_offer",obj("p_request",rid,"p_helper",helper,"p_status",state),(yes,msg,data)->{toast(yes?"Rescue updated":msg);if(yes)myCenter();});}).show());}}catch(Exception e){error("Unable to read rescue center");}});}
 private void addRow(String t,String s,View.OnClickListener l){LinearLayout c=col();c.setPadding(dp(15),dp(10),dp(15),dp(10));UiKit.card(c);c.addView(UiKit.text(this,t,16,UiKit.TEXT,true));c.addView(UiKit.text(this,s,12,UiKit.MUTED,false));if(l!=null)c.setOnClickListener(l);body.addView(c,new LinearLayout.LayoutParams(-1,-2));}private void addText(String s){TextView v=UiKit.text(this,s,13,UiKit.MUTED,false);v.setPadding(dp(8),dp(10),dp(8),dp(10));body.addView(v);}private void error(String m){status.setText(m+" • Run the v9.0 SQL migration");}private JSONObject obj(Object...p){JSONObject o=new JSONObject();try{for(int i=0;i<p.length;i+=2)o.put((String)p[i],p[i+1]);}catch(Exception e){throw new IllegalArgumentException(e);}return o;}private void rpc(String n,JSONObject b,RiderLinkClient.Callback c){client.eventRpc(n,b,c);}private LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}private EditText field(String h){EditText e=new EditText(this);UiKit.field(e);e.setHint(h);return e;}private Button button(String t,Runnable r){Button b=UiKit.iconButton(this,"",t,UiKit.SURFACE_ACTIVE);b.setOnClickListener(v->r.run());return b;}private int dp(int v){return UiKit.dp(this,v);}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}@Override protected void onDestroy(){try{manager.removeUpdates(this);}catch(Exception ignored){}client.shutdown();super.onDestroy();}
}
