package com.stankhouse.scooterspeedometer;

import android.app.*;import android.content.*;import android.graphics.Color;import android.os.Bundle;import android.view.*;import android.widget.*;

/** One premium command center for the recurring RiderLink+ network services. */
public final class RiderLinkPlusHubActivity extends Activity{
 private RiderLinkClient client;private LinearLayout body;private TextView access;
 @Override public void onCreate(Bundle b){super.onCreate(b);Fullscreen.apply(this);client=new RiderLinkClient(this);build();client.membership((ok,m,x)->access.setText(ok?(client.membershipAdmin()?"DEVELOPER • ALL RIDERLINK+ SERVICES":"RIDERLINK+ "+(client.plusActive()?"ACTIVE":"PREVIEW")):m));}
 private void build(){LinearLayout root=col();root.setPadding(dp(14),dp(8),dp(14),dp(12));root.setBackground(UiKit.screenBackground(this));LinearLayout head=UiKit.header(this,"★","RIDERLINK+","RIDE TOGETHER • GET HOME SAFE");Button close=UiKit.iconButton(this,"×","Close",UiKit.SURFACE_HIGH);close.setOnClickListener(v->finish());head.addView(close,new LinearLayout.LayoutParams(dp(82),dp(44)));root.addView(head,new LinearLayout.LayoutParams(-1,dp(76)));access=UiKit.text(this,"Checking membership…",12,UiKit.CYAN,true);access.setGravity(Gravity.CENTER);root.addView(access,new LinearLayout.LayoutParams(-1,dp(36)));body=col();ScrollView scroll=new ScrollView(this);scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);
  section("LIVE RIDING");card("⌖ LIVE GROUP RIDE","Private convoy map • leader/sweep roles • gap and regroup alerts",GroupRideActivity.class);card("➤ SCOOTER NAVIGATION","50cc • 125cc • 150cc • 250cc road profiles",BuiltInNavigationActivity.class);card("✦ RIDE GUARDIAN","Trusted riders • live trip • overdue check-ins • crash follow-up",SafetyCircleActivity.class);
  section("COMMUNITY");card("⚒ MECHANICAL RESCUE 2.0","Tools • fuel • battery • mechanical • trailer helpers",RescueNetworkActivity.class);card("☾ SMART RIDE NIGHTS","Discovery • chat • route voting • QR check-in • emergency regroup",RiderEventsActivity.class);card("▦ RIDE PASS & REPUTATION","Private rotating QR • verified activity badges",RiderIdentityActivity.class);
  section("RIDE INTELLIGENCE");card("☀ WEATHER RIDE WINDOW","Ride score • rain clock • wind and crosswind guidance",WeatherRideWindowActivity.class);card("! ROAD CONDITION INTELLIGENCE","Rider-confirmed hazards and spoken route warnings",RoadIntelActivity.class);
 }
 private void card(String title,String sub,Class<?> target){LinearLayout c=col();c.setPadding(dp(17),dp(13),dp(17),dp(13));UiKit.card(c);c.addView(UiKit.text(this,title,16,UiKit.TEXT,true));c.addView(UiKit.text(this,sub,12,UiKit.MUTED,false));c.setOnClickListener(v->{if(target==BuiltInNavigationActivity.class)chooseNavigation();else startActivity(new Intent(this,target));});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(5),0,dp(5));body.addView(c,p);}
 private void chooseNavigation(){String[] modes={"50cc • local roads, no motorway","125cc • city and county roads","150cc • broader routes, motorway discouraged","250cc • full-road capable"};new AlertDialog.Builder(this).setTitle("Scooter navigation mode").setSingleChoiceItems(modes,getSharedPreferences("speedometer",MODE_PRIVATE).getInt("nav_engine_class",0),(d,w)->{getSharedPreferences("speedometer",MODE_PRIVATE).edit().putInt("nav_engine_class",w).apply();d.dismiss();EditText destination=new EditText(this);UiKit.field(destination);destination.setHint("Where are you riding?");new AlertDialog.Builder(this).setTitle(modes[w].split(" • ")[0]+" route").setView(destination).setNegativeButton("Cancel",null).setPositiveButton("ROUTE",(x,y)->startActivity(new Intent(this,BuiltInNavigationActivity.class).putExtra("destination",destination.getText().toString().trim()))).show();}).setNegativeButton("Cancel",null).show();}
 private void section(String t){body.addView(UiKit.section(this,"◆",t));}private LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}private int dp(int v){return UiKit.dp(this,v);}@Override protected void onDestroy(){if(client!=null)client.shutdown();super.onDestroy();}
}
