package com.stankhouse.scooterspeedometer;

import android.app.*;import android.graphics.*;import android.os.*;import android.view.*;import android.widget.*;import com.google.zxing.*;import com.google.zxing.common.BitMatrix;import org.json.*;

/** Private rotating Ride Pass plus transparent, activity-based Rider Reputation. */
public final class RiderIdentityActivity extends Activity{
 private RiderLinkClient client;private LinearLayout body;
 @Override public void onCreate(Bundle b){super.onCreate(b);client=new RiderLinkClient(this);LinearLayout root=col();root.setPadding(dp(16),dp(12),dp(16),dp(12));root.setBackground(UiKit.screenBackground(this));root.addView(UiKit.header(this,"▦","RIDE PASS","Fast check-in • verified reputation"));Button back=button("‹ Events",this::finish);root.addView(back);body=col();ScrollView scroll=new ScrollView(this);scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);load(false);}
 private void load(boolean rotate){body.removeAllViews();body.addView(UiKit.text(this,"Loading your Rider identity…",14,UiKit.CYAN,true));rpc("my_ride_pass",obj("p_rotate",rotate),(ok,m,raw)->{if(!ok){showError(m);return;}String code=raw.replace("\"","").trim();rpc("my_rider_reputation",obj("p_user",JSONObject.NULL),(o,msg,reputation)->{if(!o){showError(msg);return;}try{render(code,new JSONObject(reputation));}catch(Exception e){showError("Unable to read Rider identity");}});});}
 private void render(String code,JSONObject rep){body.removeAllViews();TextView name=UiKit.text(this,rep.optString("username","Rider"),25,UiKit.TEXT,true);name.setGravity(Gravity.CENTER);body.addView(name);ImageView qr=new ImageView(this);qr.setImageBitmap(qr("riderlink://pass/"+code,720));qr.setBackgroundColor(Color.WHITE);qr.setPadding(dp(12),dp(12),dp(12),dp(12));LinearLayout.LayoutParams q=new LinearLayout.LayoutParams(-1,dp(340));q.setMargins(0,dp(12),0,dp(8));body.addView(qr,q);TextView pass=UiKit.text(this,code,27,UiKit.CYAN_BRIGHT,true);pass.setGravity(Gravity.CENTER);pass.setLetterSpacing(.16f);body.addView(pass,new LinearLayout.LayoutParams(-1,dp(55)));body.addView(UiKit.text(this,"Show this pass to a Ride Night host. Rotate it immediately if you shared it accidentally.",12,UiKit.MUTED,false));body.addView(button("Rotate Ride Pass",()->new AlertDialog.Builder(this).setTitle("Rotate your Ride Pass?").setMessage("The old code will stop working immediately.").setNegativeButton("Cancel",null).setPositiveButton("Rotate",(d,w)->load(true)).show()));body.addView(UiKit.section(this,"★","Rider reputation"));addStat("REPUTATION",rep.optInt("reputation_score"),"Activity-based; riders cannot rate or downvote each other");addStat("RIDES ATTENDED",rep.optInt("rides_attended"),"Verified Ride Night check-ins");addStat("RIDES HOSTED",rep.optInt("rides_hosted"),"Completed, non-cancelled events");addStat("ROADSIDE HELPS",rep.optInt("rescue_helps"),"Rescue offers marked completed by the requester");addStat("CONFIRMED ROAD REPORTS",rep.optInt("road_reports"),"Road intelligence confirmed by riders");}
 private void addStat(String title,int value,String sub){LinearLayout card=col();card.setPadding(dp(16),dp(12),dp(16),dp(12));UiKit.card(card);card.addView(UiKit.text(this,title+"  "+value,17,UiKit.TEXT,true));card.addView(UiKit.text(this,sub,12,UiKit.MUTED,false));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(5),0,dp(5));body.addView(card,p);}
 private Bitmap qr(String value,int size){try{BitMatrix bits=new MultiFormatWriter().encode(value,BarcodeFormat.QR_CODE,size,size);Bitmap out=Bitmap.createBitmap(size,size,Bitmap.Config.RGB_565);for(int y=0;y<size;y++)for(int x=0;x<size;x++)out.setPixel(x,y,bits.get(x,y)?Color.BLACK:Color.WHITE);return out;}catch(Exception e){return Bitmap.createBitmap(1,1,Bitmap.Config.RGB_565);}}
 private void showError(String m){body.removeAllViews();body.addView(UiKit.text(this,m+"\n\nRun the v9.0 Ride Nights SQL migration.",14,UiKit.RED,false));}private JSONObject obj(Object...p){JSONObject o=new JSONObject();try{for(int i=0;i<p.length;i+=2)o.put((String)p[i],p[i+1]);}catch(Exception e){throw new IllegalArgumentException(e);}return o;}private void rpc(String n,JSONObject b,RiderLinkClient.Callback c){client.eventRpc(n,b,c);}private LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}private Button button(String t,Runnable r){Button b=UiKit.iconButton(this,"",t,UiKit.SURFACE_ACTIVE);b.setOnClickListener(v->r.run());return b;}private int dp(int v){return UiKit.dp(this,v);}@Override protected void onDestroy(){client.shutdown();super.onDestroy();}
}
