package com.stankhouse.scooterspeedometer;

import android.app.*;import android.content.*;import android.graphics.Color;import android.os.*;import android.view.*;import android.widget.*;
import org.json.*;import java.text.*;import java.util.*;
import com.google.zxing.integration.android.IntentIntegrator;import com.google.zxing.integration.android.IntentResult;

/** One place for event chat, route voting, check-in, Convoy launch and emergency regrouping. */
public final class RideNightActivity extends Activity{
 private RiderLinkClient client;private LinearLayout body;private TextView status;private long eventId;private String title;private boolean host;private final Handler refresh=new Handler(Looper.getMainLooper());
 @Override public void onCreate(Bundle b){super.onCreate(b);eventId=getIntent().getLongExtra("event_id",0);title=getIntent().getStringExtra("event_title");client=new RiderLinkClient(this);build();load();}
 private void build(){LinearLayout root=col();root.setPadding(dp(12),dp(10),dp(12),dp(8));root.setBackground(UiKit.screenBackground(this));root.addView(UiKit.header(this,"☾","RIDE NIGHT",title==null?"Live event hub":title));Button back=button("‹ Events",this::finish);root.addView(back);status=UiKit.text(this,"Loading Ride Night…",13,UiKit.CYAN,true);root.addView(status,new LinearLayout.LayoutParams(-1,dp(38)));body=col();ScrollView scroll=new ScrollView(this);scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
 private void load(){rpc("ride_night_snapshot",obj("p_event",eventId),(ok,m,b)->{if(!ok){status.setText(m+" • Run the v9.0 migration");return;}try{render(new JSONObject(b));}catch(Exception e){status.setText("Could not read Ride Night");}});}
 private void render(JSONObject snap)throws Exception{body.removeAllViews();JSONObject event=snap.getJSONObject("event");host=client.userId().equals(event.optString("host_id"));status.setText((host?"HOST • ":"")+snap.optInt("checkins")+" checked in");
  addSection("LIVE CONTROLS");addRow("✓ Check in","Earn verified attendance reputation",v->checkIn());addRow("⌖ Navigate",event.optString("meeting_place"),v->navigate(event.optString("meeting_place")+", "+event.optString("city")));addRow("♟ Event chat","Announcements and rider messages",v->chat());
  if(host){addRow("⚑ Launch Convoy","Create a live convoy using the winning route",v->launchConvoy(snap.optJSONArray("routes")));addRow("! Emergency meet-point","Broadcast a safe regroup location",v->meetPoint());addRow("▦ Scan Ride Pass","Scan QR or enter the 10-character fallback",v->ridePassMenu());}
  addSection("ROUTE VOTING");JSONArray routes=snap.optJSONArray("routes");if(routes==null||routes.length()==0)addText("No routes proposed yet.");else for(int i=0;i<routes.length();i++){JSONObject route=routes.getJSONObject(i);long oid=route.getLong("id");String sub=route.optString("destination")+" • "+route.optInt("votes")+" votes"+(route.optBoolean("locked")?" • LOCKED":"");addRow((route.optBoolean("my_vote")?"✓ ":"")+route.optString("label"),sub,v->routeMenu(oid,route.optString("label")));}addRow("+ Propose route","Going riders can add up to 10 options",v->propose());
  JSONObject meet=snap.optJSONObject("meet_point");if(meet!=null){addSection("EMERGENCY MEET-POINT");addRow(meet.optString("label"),meet.optString("address"),v->navigate(meet.optString("address")));}
 }
 private void checkIn(){rpc("check_in_ride_night",obj("p_event",eventId,"p_pass",JSONObject.NULL),(o,m,b)->{toast(o?"Ride Night check-in confirmed":m);if(o)load();});}
 private void routeMenu(long option,String label){ArrayList<String> items=new ArrayList<>();items.add("Vote for this route");if(host)items.add("Lock as final route");new AlertDialog.Builder(this).setTitle(label).setItems(items.toArray(new String[0]),(d,w)->{String fn=w==0?"vote_ride_route":"lock_ride_route";rpc(fn,obj("p_event",eventId,"p_option",option),(o,m,b)->{toast(o?(w==0?"Vote saved":"Final route locked"):m);if(o)load();});}).show();}
 private void propose(){LinearLayout form=col();EditText name=field("Route name"),dest=field("Destination or final stop"),miles=field("Approx. miles (optional)");miles.setInputType(2|8192);form.addView(name);form.addView(dest);form.addView(miles);new AlertDialog.Builder(this).setTitle("Propose route").setView(form).setNegativeButton("Cancel",null).setPositiveButton("Add",(d,w)->{Double distance=null;try{if(!miles.getText().toString().trim().isEmpty())distance=Double.valueOf(miles.getText().toString());}catch(Exception ignored){}rpc("propose_ride_route",obj("p_event",eventId,"p_label",name.getText().toString(),"p_destination",dest.getText().toString(),"p_miles",distance==null?JSONObject.NULL:distance),(o,m,b)->{toast(o?"Route added":m);if(o)load();});}).show();}
 private void chat(){final LinearLayout feed=col();final EditText input=field("Message the Ride Night");final CheckBox announcement=new CheckBox(this);announcement.setText("Host announcement");announcement.setTextColor(UiKit.AMBER);announcement.setVisibility(host?View.VISIBLE:View.GONE);ScrollView scroll=new ScrollView(this);scroll.addView(feed);LinearLayout panel=col();panel.setPadding(dp(12),0,dp(12),0);panel.addView(scroll,new LinearLayout.LayoutParams(-1,dp(360)));panel.addView(input);panel.addView(announcement);AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Ride Night chat").setView(panel).setNegativeButton("Close",null).setPositiveButton("Send",null).create();Runnable reload=()->rpc("ride_night_messages",obj("p_event",eventId,"p_after",0),(ok,m,b)->{if(!ok)return;feed.removeAllViews();try{JSONArray a=new JSONArray(b);for(int i=0;i<a.length();i++){JSONObject x=a.getJSONObject(i);TextView row=UiKit.text(this,(x.optBoolean("announcement")?"📢 HOST • ":"")+x.optString("username")+"\n"+x.optString("body"),14,x.optBoolean("announcement")?UiKit.AMBER:UiKit.TEXT,false);row.setPadding(dp(8),dp(8),dp(8),dp(8));feed.addView(row);}}catch(Exception ignored){}});dialog.setOnShowListener(v->{reload.run();dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(send->{String message=input.getText().toString().trim();if(message.isEmpty())return;rpc("post_ride_night_chat",obj("p_event",eventId,"p_body",message,"p_announcement",announcement.isChecked()),(o,m,b)->{if(o){input.setText("");announcement.setChecked(false);reload.run();}else toast(m);});});});dialog.show();}
 private void meetPoint(){LinearLayout form=col();EditText label=field("Safe place name"),address=field("Full address or clear location");form.addView(label);form.addView(address);new AlertDialog.Builder(this).setTitle("Emergency meet-point").setMessage("This broadcasts a pinned host announcement to every event member.").setView(form).setNegativeButton("Cancel",null).setPositiveButton("Broadcast",(d,w)->rpc("set_emergency_meet_point",obj("p_event",eventId,"p_label",label.getText().toString(),"p_address",address.getText().toString(),"p_lat",JSONObject.NULL,"p_lon",JSONObject.NULL),(o,m,b)->{toast(o?"Emergency meet-point broadcast":m);if(o)load();})).show();}
 private void ridePassMenu(){new AlertDialog.Builder(this).setTitle("Ride Pass check-in").setItems(new String[]{"Scan QR code","Enter fallback code"},(d,w)->{if(w==0)new IntentIntegrator(this).setDesiredBarcodeFormats(IntentIntegrator.QR_CODE).setPrompt("Scan the rider's RiderLink Ride Pass").setBeepEnabled(true).setOrientationLocked(false).initiateScan();else enterPass();}).show();}
 private void enterPass(){EditText code=field("10-character Ride Pass");new AlertDialog.Builder(this).setTitle("Check in Ride Pass").setView(code).setNegativeButton("Cancel",null).setPositiveButton("Check in",(d,w)->checkPass(code.getText().toString())).show();}
 private void checkPass(String raw){String code=raw==null?"":raw.trim();int slash=code.lastIndexOf('/');if(code.startsWith("riderlink://pass/")&&slash>=0)code=code.substring(slash+1);code=code.toUpperCase(Locale.US);if(!code.matches("[A-Z0-9]{10}")){toast("That is not a RiderLink Ride Pass");return;}rpc("check_in_ride_night",obj("p_event",eventId,"p_pass",code),(o,m,b)->{toast(o?"Rider checked in":m);if(o)load();});}
 @Override protected void onActivityResult(int requestCode,int resultCode,Intent data){IntentResult result=IntentIntegrator.parseActivityResult(requestCode,resultCode,data);if(result!=null){if(result.getContents()!=null)checkPass(result.getContents());return;}super.onActivityResult(requestCode,resultCode,data);}
 private void launchConvoy(JSONArray routes){String destination="Ride Night route";if(routes!=null)for(int i=0;i<routes.length();i++){JSONObject r=routes.optJSONObject(i);if(r!=null&&r.optBoolean("locked")){destination=r.optString("destination",destination);break;}}final String dest=destination;new AlertDialog.Builder(this).setTitle("Launch live Convoy?").setMessage("Creates a temporary Convoy for this Ride Night using: "+dest).setNegativeButton("Cancel",null).setPositiveButton("Launch",(d,w)->client.createConvoy(title==null?"Ride Night":title,dest,true,(o,m,b)->{if(o){toast("Convoy launched");startActivity(new Intent(this,GroupRideActivity.class));}else toast(m);})).show();}
 private void navigate(String destination){startActivity(new Intent(this,BuiltInNavigationActivity.class).putExtra("destination",destination));}
 private void addSection(String t){body.addView(UiKit.section(this,"◆",t));}private void addText(String t){TextView v=UiKit.text(this,t,13,UiKit.MUTED,false);v.setPadding(dp(12),dp(8),dp(12),dp(8));body.addView(v);}private void addRow(String t,String s,View.OnClickListener l){LinearLayout c=col();c.setPadding(dp(16),dp(10),dp(16),dp(10));UiKit.card(c);c.addView(UiKit.text(this,t,16,UiKit.TEXT,true));c.addView(UiKit.text(this,s,12,UiKit.MUTED,false));c.setOnClickListener(l);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(4),0,dp(4));body.addView(c,p);}
 private JSONObject obj(Object... p){JSONObject o=new JSONObject();try{for(int i=0;i<p.length;i+=2)o.put((String)p[i],p[i+1]);}catch(Exception e){throw new IllegalArgumentException(e);}return o;}private void rpc(String n,JSONObject b,RiderLinkClient.Callback c){client.eventRpc(n,b,c);}private LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}private EditText field(String h){EditText e=new EditText(this);UiKit.field(e);e.setHint(h);return e;}private Button button(String t,Runnable r){Button b=UiKit.iconButton(this,"",t,UiKit.SURFACE_ACTIVE);b.setOnClickListener(v->r.run());return b;}private int dp(int v){return UiKit.dp(this,v);}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
 @Override protected void onDestroy(){refresh.removeCallbacksAndMessages(null);client.shutdown();super.onDestroy();}
}
