package com.stankhouse.scooterspeedometer;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.location.*;import android.os.*;import android.view.*;import android.widget.*;import org.json.*;import java.util.*;

/** Community-confirmed scooter road conditions with expiration and anti-spam limits. */
public final class RoadIntelActivity extends Activity implements LocationListener{
 private RiderLinkClient client;private LocationManager manager;private Location fix;private LinearLayout body;private TextView status;
 @Override public void onCreate(Bundle b){super.onCreate(b);client=new RiderLinkClient(this);manager=(LocationManager)getSystemService(LOCATION_SERVICE);LinearLayout root=col();root.setPadding(dp(14),dp(10),dp(14),dp(8));root.setBackground(UiKit.screenBackground(this));root.addView(UiKit.header(this,"⚠","ROAD INTELLIGENCE","Rough • gravel • flooding • closures"));root.addView(button("‹ Events",this::finish));status=UiKit.text(this,"Waiting for GPS…",13,UiKit.CYAN,true);root.addView(status);LinearLayout actions=new LinearLayout(this);actions.addView(button("Report here",this::report),new LinearLayout.LayoutParams(0,dp(52),1));actions.addView(button("Refresh nearby",this::load),new LinearLayout.LayoutParams(0,dp(52),1));root.addView(actions);body=col();ScrollView scroll=new ScrollView(this);scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);requestLocation();}
 private void requestLocation(){if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION},72);return;}try{manager.requestLocationUpdates(LocationManager.GPS_PROVIDER,1000,0,this);Location last=manager.getLastKnownLocation(LocationManager.GPS_PROVIDER);if(last!=null)onLocationChanged(last);}catch(SecurityException ignored){}}
 @Override public void onLocationChanged(Location l){if(l.hasAccuracy()&&l.getAccuracy()<120){fix=l;status.setText(String.format(Locale.US,"GPS ready • ±%.0f m",l.getAccuracy()));}}
 private void load(){if(fix==null){toast("Wait for a GPS fix");return;}body.removeAllViews();status.setText("Loading road conditions within 15 km…");rpc("nearby_road_intel",obj("p_lat",fix.getLatitude(),"p_lon",fix.getLongitude(),"p_radius_km",15),(ok,m,b)->{if(!ok){status.setText(m+" • Run v9.0 SQL");return;}try{JSONArray a=new JSONArray(b);status.setText(a.length()+" active road reports");if(a.length()==0)addText("Roads are clear—or nobody has reported conditions yet.");for(int i=0;i<a.length();i++){JSONObject r=a.getJSONObject(i);long id=r.getLong("id");String destination=r.getDouble("latitude")+","+r.getDouble("longitude");String subtitle="Severity "+r.optInt("severity")+" • "+r.optInt("confirmations")+" confidence • "+String.format(Locale.US,"%.1f km",r.optDouble("distance_km"));if(!r.optString("note").isEmpty())subtitle+="\n"+r.optString("note");addRow(r.optString("report_type").replace('_',' ').toUpperCase(Locale.US),subtitle,v->new AlertDialog.Builder(this).setTitle("Road report").setItems(new String[]{"Confirm accurate","Mark cleared / inaccurate","Navigate there"},(d,w)->{if(w==2)startActivity(new Intent(this,BuiltInNavigationActivity.class).putExtra("destination",destination));else rpc("vote_road_intel",obj("p_report",id,"p_accurate",w==0),(o,msg,data)->{toast(o?"Road intelligence updated":msg);if(o)load();});}).show());}}catch(Exception e){status.setText("Unable to read road reports");}});}
 private void report(){if(fix==null){toast("Wait for a GPS fix before reporting");return;}String[] labels={"Rough pavement","Gravel","Flooding","Construction","Dangerous intersection","High-speed road","Closure","Debris"};String[] values={"rough","gravel","flooding","construction","dangerous_intersection","high_speed","closure","debris"};new AlertDialog.Builder(this).setTitle("Road condition at your location").setItems(labels,(d,type)->new AlertDialog.Builder(this).setTitle("Severity").setItems(new String[]{"1 • Caution","2 • Avoid if possible","3 • Dangerous / blocked"},(x,severity)->{EditText note=field("Optional details");new AlertDialog.Builder(this).setTitle(labels[type]).setMessage("Report only while safely stopped.").setView(note).setNegativeButton("Cancel",null).setPositiveButton("Post report",(a,z)->rpc("report_road_intel",obj("p_type",values[type],"p_severity",severity+1,"p_note",note.getText().toString(),"p_lat",fix.getLatitude(),"p_lon",fix.getLongitude()),(o,m,b)->{toast(o?"Road intelligence posted":m);if(o)load();})).show();}).show()).show();}
 private void addRow(String t,String s,View.OnClickListener l){LinearLayout c=col();c.setPadding(dp(15),dp(11),dp(15),dp(11));UiKit.card(c);c.addView(UiKit.text(this,t,16,UiKit.TEXT,true));c.addView(UiKit.text(this,s,12,UiKit.MUTED,false));c.setOnClickListener(l);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(4),0,dp(4));body.addView(c,p);}private void addText(String s){TextView v=UiKit.text(this,s,13,UiKit.MUTED,false);v.setPadding(dp(10),dp(14),dp(10),dp(14));body.addView(v);}private JSONObject obj(Object...p){JSONObject o=new JSONObject();try{for(int i=0;i<p.length;i+=2)o.put((String)p[i],p[i+1]);}catch(Exception e){throw new IllegalArgumentException(e);}return o;}private void rpc(String n,JSONObject b,RiderLinkClient.Callback c){client.eventRpc(n,b,c);}private LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}private EditText field(String h){EditText e=new EditText(this);UiKit.field(e);e.setHint(h);return e;}private Button button(String t,Runnable r){Button b=UiKit.iconButton(this,"",t,UiKit.SURFACE_ACTIVE);b.setOnClickListener(v->r.run());return b;}private int dp(int v){return UiKit.dp(this,v);}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}@Override protected void onDestroy(){try{manager.removeUpdates(this);}catch(Exception ignored){}client.shutdown();super.onDestroy();}
}
