package com.stankhouse.scooterspeedometer;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.location.*;import android.os.*;import androidx.core.app.ActivityCompat;import androidx.core.app.NotificationCompat;import org.json.*;import java.text.*;import java.util.*;

/** Foreground, opt-in location publisher for an active Safety Circle trip. */
public final class SafetyTripService extends Service implements LocationListener{
    public static final String ACTION_STOP="com.stankhouse.scooterspeedometer.STOP_SAFETY_TRIP";private static final int ID=880;private LocationManager locations;private RiderLinkClient client;private long lastSent,lastOverdueAlert;
    @Override public void onCreate(){super.onCreate();client=new RiderLinkClient(this);locations=(LocationManager)getSystemService(LOCATION_SERVICE);createChannel();}
    @Override public int onStartCommand(Intent intent,int flags,int startId){if(intent!=null&&ACTION_STOP.equals(intent.getAction())){client.endSafetyTrip((o,m,b)->stopSelf());return START_NOT_STICKY;}startForeground(ID,notification());if(ActivityCompat.checkSelfPermission(this,Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED)locations.requestLocationUpdates(LocationManager.GPS_PROVIDER,3000,3,this);return START_STICKY;}
    private Notification notification(){Intent stop=new Intent(this,SafetyTripService.class).setAction(ACTION_STOP);PendingIntent p=PendingIntent.getService(this,88,stop,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);return new NotificationCompat.Builder(this,"safety_circle").setSmallIcon(R.drawable.ic_launcher).setContentTitle("Safety Circle trip is live").setContentText("Trusted contacts can follow this ride").setOngoing(true).setOnlyAlertOnce(true).addAction(0,"END TRIP",p).build();}
    private void createChannel(){if(Build.VERSION.SDK_INT>=26)((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).createNotificationChannel(new NotificationChannel("safety_circle","Safety Circle",NotificationManager.IMPORTANCE_LOW));}
    @Override public void onLocationChanged(Location l){long now=System.currentTimeMillis();if(now-lastSent<5000)return;lastSent=now;client.updateSafetyTrip(l.getLatitude(),l.getLongitude(),l.hasAccuracy()?l.getAccuracy():0,l.hasSpeed()?l.getSpeed():0,(o,m,b)->{});if(now-lastOverdueAlert>60000)client.safetyStatus((ok,m,b)->{if(!ok)return;try{JSONArray a=new JSONArray(b);if(a.length()==0)return;String due=a.getJSONObject(0).optString("checkin_due_at","");SimpleDateFormat f=new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss",Locale.US);f.setTimeZone(TimeZone.getTimeZone("UTC"));if(!due.isEmpty()&&f.parse(due.substring(0,19)).getTime()<System.currentTimeMillis()){lastOverdueAlert=System.currentTimeMillis();client.triggerSafetyEvent("overdue","Rider missed a scheduled Safety Circle check-in",l.getLatitude(),l.getLongitude(),(x,y,z)->{});postOverdue();}}catch(Exception ignored){}});}
    private void postOverdue(){Notification n=new NotificationCompat.Builder(this,"safety_circle").setSmallIcon(R.drawable.ic_launcher).setContentTitle("Safety Circle check-in overdue").setContentText("Open the app and tap I’M OKAY").setPriority(NotificationCompat.PRIORITY_HIGH).setAutoCancel(true).build();((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).notify(881,n);}
    @Override public void onProviderEnabled(String p){}@Override public void onProviderDisabled(String p){}@Override public void onStatusChanged(String p,int s,Bundle b){}
    @Override public void onDestroy(){if(locations!=null)locations.removeUpdates(this);if(client!=null)client.shutdown();super.onDestroy();}
    @Override public IBinder onBind(Intent i){return null;}
}
