package com.stankhouse.scooterspeedometer;

import android.app.*;import android.content.*;import android.graphics.Color;import android.os.*;import android.view.*;import android.widget.*;import org.json.*;import java.text.*;import java.util.*;

public final class SafetyCircleActivity extends Activity{
    private RiderLinkClient client;private LinearLayout body;private TextView status;private final Handler refresh=new Handler(Looper.getMainLooper());
    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.rgb(2,15,20));client=new RiderLinkClient(this);build();load();}
    private void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(14),dp(16),dp(12));root.setBackground(UiKit.screenBackground(this));root.addView(UiKit.header(this,"✦","SAFETY CIRCLE","Trusted riders • live trips • check-ins"),new LinearLayout.LayoutParams(-1,dp(78)));status=UiKit.text(this,"Checking RiderLink…",14,Color.rgb(122,215,231),true);root.addView(status,new LinearLayout.LayoutParams(-1,dp(42)));body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);ScrollView scroll=new ScrollView(this);scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));TextView warning=UiKit.text(this,"Safety Circle alerts trusted contacts only. It does not call 911 or guarantee emergency response.",11,Color.rgb(145,158,164),false);warning.setGravity(Gravity.CENTER);root.addView(warning,new LinearLayout.LayoutParams(-1,dp(50)));setContentView(root);}
    private void load(){if(!client.signedIn()){status.setText("Sign in to RiderLink first");return;}client.safetyStatus((ok,m,b)->{if(!ok){status.setText(m);return;}renderStatus(b);});}
    private void renderStatus(String raw){body.removeAllViews();boolean active=false;long due=0;try{JSONArray a=new JSONArray(raw);if(a.length()>0){JSONObject s=a.getJSONObject(0);active=s.optBoolean("active");due=parseTime(s.optString("checkin_due_at"));}}catch(Exception ignored){}status.setText(active?"● LIVE TRIP • check-in "+relative(due):"○ No active safety trip");if(active){addButton("✓  I’M OKAY — CHECK IN",Color.rgb(5,132,151),v->client.checkInSafetyTrip((o,m,b)->{toast(o?"Check-in confirmed":m);load();}));addButton("■  END LIVE TRIP",Color.rgb(92,46,50),v->confirmEnd());}else addButton("▶  START LIVE SAFETY TRIP",Color.rgb(5,132,151),v->chooseInterval());addButton("＋  ADD TRUSTED RIDER",Color.rgb(25,65,76),v->addContact());addLabel("TRUSTED CONTACTS");client.safetyCircle((ok,m,b)->renderContacts(ok?b:"[]"));}
    private void renderContacts(String raw){try{JSONArray a=new JSONArray(raw);if(a.length()==0){addCard("No trusted riders yet","Add a RiderLink username. They must accept before any location is shared.",null);return;}for(int i=0;i<a.length();i++){JSONObject c=a.getJSONObject(i);String id=c.optString("contact_id"),name=c.optString("username","Rider"),scooter=c.optString("scooter",""),state=c.optString("status","pending"),direction=c.optString("direction","outgoing");long relation=c.optLong("relation_id");if("pending".equals(state)&&"incoming".equals(direction)){addCard(name,"Wants to join your Safety Circle • tap to review",v->new AlertDialog.Builder(this).setTitle("Trust "+name+"?").setMessage("Accepting allows both of you to see active safety trips and emergency events.").setPositiveButton("Accept",(d,w)->client.acceptSafetyContact(relation,(o,m,b)->{toast(o?"Safety Circle accepted":m);load();})).setNegativeButton("Not now",null).show());}else{String detail="pending".equals(state)?"Invitation pending":(scooter.isEmpty()?"Trusted Safety Circle rider":scooter);addCard(name,detail,v->new AlertDialog.Builder(this).setTitle(name).setItems(new String[]{"Remove from Safety Circle"},(d,w)->client.removeSafetyContact(id,(o,m,b)->{toast(o?"Removed":m);load();})).setNegativeButton("Cancel",null).show());}}}catch(Exception e){addCard("Unable to load contacts",e.getMessage(),null);}}
    private void chooseInterval(){String[] options={"15 minutes","30 minutes","60 minutes"};new AlertDialog.Builder(this).setTitle("Check-in interval").setMessage("Your location is shared only while this live trip is active.").setItems(options,(d,w)->client.startSafetyTrip(new int[]{15,30,60}[w],(ok,m,b)->{if(ok){Intent s=new Intent(this,SafetyTripService.class);if(Build.VERSION.SDK_INT>=26)startForegroundService(s);else startService(s);toast("Safety trip started");load();}else toast(m);})).setNegativeButton("Cancel",null).show();}
    private void confirmEnd(){new AlertDialog.Builder(this).setTitle("End live trip?").setMessage("Location sharing with your Safety Circle will stop.").setPositiveButton("End trip",(d,w)->client.endSafetyTrip((o,m,b)->{stopService(new Intent(this,SafetyTripService.class));toast(o?"Trip ended":m);load();})).setNegativeButton("Keep riding",null).show();}
    private void addContact(){EditText e=new EditText(this);e.setHint("Exact RiderLink username");e.setSingleLine();new AlertDialog.Builder(this).setTitle("Add trusted rider").setMessage("This person will be able to see active Safety Circle trips and emergency events.").setView(e).setPositiveButton("Add",(d,w)->client.addSafetyContact(e.getText().toString().trim(),(o,m,b)->{toast(o?"Trusted rider added":m);load();})).setNegativeButton("Cancel",null).show();}
    private void addLabel(String t){TextView v=UiKit.text(this,t,12,Color.rgb(112,196,210),true);v.setPadding(dp(8),dp(22),0,dp(8));body.addView(v);}
    private void addButton(String t,int color,View.OnClickListener l){TextView v=UiKit.text(this,t,15,Color.WHITE,true);v.setGravity(Gravity.CENTER);v.setBackground(UiKit.rounded(this,color,22,Color.rgb(40,99,113)));v.setOnClickListener(l);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(58));p.setMargins(0,dp(6),0,dp(6));body.addView(v,p);}
    private void addCard(String title,String sub,View.OnClickListener l){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(18),dp(13),dp(18),dp(13));c.setBackground(UiKit.rounded(this,Color.rgb(5,27,35),18,Color.rgb(31,73,85)));c.addView(UiKit.text(this,title,17,Color.WHITE,true));c.addView(UiKit.text(this,sub,12,Color.rgb(145,169,176),false));if(l!=null)c.setOnClickListener(l);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(76));p.setMargins(0,dp(5),0,dp(5));body.addView(c,p);}
    private long parseTime(String s){try{return new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss",Locale.US).parse(s.substring(0,19)).getTime();}catch(Exception e){return 0;}}
    private String relative(long t){long min=(t-System.currentTimeMillis())/60000;return min<0?"OVERDUE":Math.max(1,min)+" min";}
    private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}private int dp(int v){return UiKit.dp(this,v);}
    @Override protected void onResume(){super.onResume();refresh.postDelayed(new Runnable(){public void run(){load();refresh.postDelayed(this,15000);}},15000);}@Override protected void onPause(){refresh.removeCallbacksAndMessages(null);super.onPause();}@Override protected void onDestroy(){client.shutdown();super.onDestroy();}
}
