package com.stankhouse.scooterspeedometer;

import android.Manifest;import android.app.*;import android.content.pm.PackageManager;import android.graphics.Color;import android.location.*;import android.os.Bundle;import android.view.Gravity;import android.widget.*;import java.text.*;import java.util.*;

/** Rider-oriented weather verdict using live precipitation, gust and visibility conditions. */
public final class WeatherRideWindowActivity extends Activity implements LocationListener{
 private WeatherRepository weather;private LocationManager manager;private TextView verdict,details;private Location fix;
 @Override public void onCreate(Bundle b){super.onCreate(b);Fullscreen.apply(this);weather=new WeatherRepository(this);manager=(LocationManager)getSystemService(LOCATION_SERVICE);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(10),dp(16),dp(12));root.setBackground(UiKit.screenBackground(this));root.addView(UiKit.header(this,"☀","WEATHER RIDE WINDOW","WHEN TO RIDE • WHEN TO WAIT"));Button back=UiKit.iconButton(this,"‹","RiderLink+",UiKit.SURFACE_HIGH);back.setOnClickListener(v->finish());root.addView(back,new LinearLayout.LayoutParams(-1,dp(50)));verdict=UiKit.text(this,"Finding your safest ride window…",24,UiKit.TEXT,true);verdict.setGravity(Gravity.CENTER);root.addView(verdict,new LinearLayout.LayoutParams(-1,dp(100)));details=UiKit.text(this,"GPS weather uses your current riding area.",15,UiKit.MUTED,false);details.setPadding(dp(18),dp(18),dp(18),dp(18));details.setBackground(UiKit.rounded(this,Color.rgb(5,27,35),20,Color.rgb(31,73,85)));root.addView(details,new LinearLayout.LayoutParams(-1,-2));TextView note=UiKit.text(this,"The score is riding guidance, not a guarantee. Check local alerts and road conditions before leaving.",11,UiKit.MUTED,false);note.setPadding(0,dp(18),0,0);root.addView(note);setContentView(root);startGps();}
 private void startGps(){if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION},93);return;}try{manager.requestSingleUpdate(LocationManager.GPS_PROVIDER,this,null);Location l=manager.getLastKnownLocation(LocationManager.GPS_PROVIDER);if(l!=null)onLocationChanged(l);}catch(Exception e){verdict.setText("GPS unavailable");}}
 @Override public void onLocationChanged(Location l){fix=l;weather.update(l.getLatitude(),l.getLongitude(),this::render);weather.updateAlerts(l.getLatitude(),l.getLongitude(),a->{if(a!=null&&a.active()&&a.severityRank()>=2)details.append("\n\n⚠ "+a.event+" • "+a.severity+"\n"+a.headline);});}
 private void render(WeatherRepository.WeatherData w){int score=100;score-=Math.min(50,w.rainChance/2);score-=Math.min(35,(int)Math.max(0,w.upcomingWindGust-15)*2);if(w.weatherCode>=95)score-=50;else if(w.weatherCode==45||w.weatherCode==48)score-=25;if(w.feelsLike<35)score-=Math.min(25,(int)(35-w.feelsLike));if(w.feelsLike>95)score-=Math.min(20,(int)(w.feelsLike-95));score=Math.max(0,Math.min(100,score));String grade=score>=80?"HELL YEAH — GOOD RIDE WINDOW":score>=60?"RIDEABLE — USE CAUTION":score>=40?"SHORT RIDES ONLY":"WAIT IT OUT";verdict.setText(score+"/100\n"+grade);verdict.setTextColor(score>=80?Color.rgb(55,225,160):score>=60?UiKit.AMBER:UiKit.RED);String rain=w.precipitationMinutes<0?"No rain detected in the next hour":w.precipitationMinutes==0?"Precipitation is starting now":"Precipitation may begin in "+w.precipitationMinutes+" minutes";String wind=w.upcomingWindGust>=30?"Strong gust risk — exposed roads and crosswinds are dangerous":w.upcomingWindGust>=20?"Moderate gusts — watch crosswinds":"Wind is manageable for most scooters";details.setText(w.icon()+"  "+w.condition()+" • "+Math.round(w.temperature)+"°F\nFeels like "+Math.round(w.feelsLike)+"°F\n\n☂ "+rain+" • "+w.rainChance+"%\n➤ Wind "+Math.round(w.windSpeed)+" mph "+w.windCompass()+" • gusts "+Math.round(w.upcomingWindGust)+" mph\n\n"+wind+"\n\nUpdated "+new SimpleDateFormat("h:mm a",Locale.US).format(new Date(w.updatedAt)));}
 private int dp(int v){return UiKit.dp(this,v);}@Override public void onProviderEnabled(String p){}@Override public void onProviderDisabled(String p){}@Override public void onStatusChanged(String p,int s,Bundle b){}@Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==93&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)startGps();}
}
